### PR TITLE
Update setuptools and zc.buildout

### PR DESCRIPTION
**Pull request by gforcada**
The first to 8.3 and the later to latest one available (2.3.1).

### CODE REVIEW

**Comment by gforcada** [comment]
Testing http://jenkins.plone.org/job/pull-request/205

**Comment by vangheem** [comment]
Should we not set a setuptools version? zc.buildout + setuptools + virtualenv setuptools version can be painful.

**Comment by gforcada** [comment]
@vangheem at least until we use a newer version of a CMF package (I think CMFCore that @mauritsvanrees fixed) we are stuck at 5.8/8.3... anything above that (in setuptools) breaks our builds

**Comment by gforcada** [comment]
@vangheem and at the end pinning versions is what we do with everything, so why setupools, specially now given their relative high development peace, should be different?

**Comment by vangheem** [comment]
Yah, the old reason would be because of the pain and potential issues you get from pinning that setuptools.

**Comment by gforcada** [comment]
@vangheem so it seems that even 8.3 is _too_ new: http://jenkins.plone.org/job/pull-request/205/testReport/ so yes, :+1: for pinning everything :)

**Comment by vangheem** [comment]
man, that's lame.

**Comment by thet** [comment]
@gforcada did you try with the latest setuptools? IIRC, around 8.something, they changed the versioning policy to be PEP440 compliant. later on, they added backwards compatibility for pre 8.something versions.

**Comment by gforcada** [comment]
@thet no, apart from 5.8 and 8.3 which already breaks, I haven't tried anything else so far, let's give it a try though...

**Comment by tisto** [comment]
Testing setuptools 17.0: https://github.com/plone/buildout.coredev/pull/84

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request/208/

**Comment by tisto** [comment]
Had to revert. Sorry for the noise. See https://github.com/plone/Products.CMFPlone/issues/403 for details.

**Comment by mauritsvanrees** [comment]
The problem is that we need a new GenericSetup release (that will be 1.7.6 once released), because that will sort the upgrade steps correctly with both old and new versions of setuptools.

At the end of May, Tres Seaver has moved the CMF repos from svn.zope.org to github.com/zopefoundation (and launchpad as readonly backup that will be synced). The dust needs to settle a bit before a new release. The core CMF buildout needs some love for a failing CI test: http://permalink.gmane.org/gmane.comp.web.zope.cmf/19239

**Pull request merged**
