### PR TITLE
Update 6.0 branch to use Zope 5.0a2 and newer versions of other dependencies

### PR DESCRIPTION
**Pull request by jensens**
I left `Pillow` and `z3c.form` untouched so far.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
`Products.validation` is also used by `collective.easyform`. It works fine on Plone 5.2 with Python 3.

**Comment by jensens** [comment]
Oh. then we need to fix its deprecated App.init import...

Or (w/o having a look at it) fixing easyform to not use this aged package?

**Comment by jensens** [comment]
Well, I just found ``collective.easyform`` is not officially in the ecosystem section so we either add it or remove Products.validation, otherwise this is not consistent.

**Comment by jensens** [comment]
see also https://github.com/plone/Products.validation/pull/7 for a fixed Products.validation

**Comment by ale-rt** [comment]
I was looking plone.app.caching.tests.test_integration.TestOperations.test_controlpanel.

It seems to me it might be an issue related to how the record inputs are processed.
See the bytes here:
```
(Pdb) pp dict(self.request.form["templates"])
{'plone-content-feed': [b'search_rss',
                        b'RSS',
                        b'atom.xml',
                        b'rss.xml',
                        b'itunes.xml'],
 'plone-content-file': [],
 'plone-content-folderView': [],
 'plone-content-itemView': [b'sitemap',
                            b'accessibility-info',
                            b'file_view',
                            b'image_view',
                            b'image_view_fullscreen'],
 'plone-resource': [],
 'plone-stableResource': []}
```

**Comment by ale-rt** [comment]
I think I spotted the error:
```
> /home/ale/Code/plone/projects/coredev/.tox/py37-plone60/src/plone.z3cform/src/plone/z3cform/z2.py(69)_decode()
-> return HTTPRequest._decode(text, charset)
(Pdb) l
 64
 65     def _decode(text, charsets):
 66         for charset in charsets:
 67             try:
 68                 # decode recursively
 69  ->             return HTTPRequest._decode(text, charset)
 70             except (UnicodeError, AttributeError):
 71                 pass
 72         return text
 73
 74
(Pdb) HTTPRequest._decode(text, charset)
*** AttributeError: module 'ZPublisher.HTTPRequest' has no attribute '_decode'
```

**Comment by ale-rt** [comment]
Note the function was removed here https://github.com/zopefoundation/Zope/commit/72d046a00a0f293088a4ccdc0a472cf7ca9b0847
Probably just copying the removed code in plone.z3cform will fix this :)
But not tonight :p

**Comment by jensens** [comment]
I close this in favour of a new branch.

**Pull request closed without merging**
