### PR TITLE
4.3.x csrffixes

### PR DESCRIPTION
**Pull request by gforcada**
Second try after the first attempt (https://github.com/plone/buildout.coredev/pull/132).

Now that pull request job for 4.3 should work just like the regular 4.3 jobs, we should not be able to merge with tests breaking.

**[EDIT]**
prior to this one we need to merge:
- [ ] https://github.com/plone/plone.contentrules/pull/4 (into master, must work in 5.x as well)
- [ ] https://github.com/plone/plone.app.imaging/pull/24
- [ ] https://github.com/plone/Products.CMFPlone/pull/1305
- [ ] https://github.com/plone/Products.ATContentTypes/issues/29

after merge in this branch the sources must be changed back to the series branches

### CODE REVIEW

**Comment by gforcada** [comment]
@plone/release-team my first attempt at merging resulted in lots of errors (which I reverted back to get a green build).

So we still can not release a 4.3.8 with all the hotfixes unfortunately.

**Comment by jensens** [comment]
:( this was unexpected. 
It also looks like jenkins does not report back, i.e. http://jenkins.plone.org/job/pull-request-4.3/189/ failed, but github check status is still pending.

**Comment by jensens** [comment]
Total time elapsed: 2345.186 seconds
Grand total: 125 packages, 0 failures

BUT then we get

```
...
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Robot results publisher started...
-Parsing output xml:
Failed!
hudson.AbortException: No files found in path /home/jenkins/workspace/pull-request-4.3/parts/test with configured filemask: robot_output.xml
...
```

**Comment by gforcada** [comment]
@jensens there was another error on the pull request 4.3 job, should be fixed now... I have to take a look at the robot thing though

**Comment by jensens** [comment]
prior to this one we need to merge:
- [ ] https://github.com/plone/plone.contentrules/pull/4 (into master, must work in 5.x as well)
- [ ] https://github.com/plone/plone.app.imaging/pull/24
- [ ] https://github.com/plone/Products.CMFPlone/pull/1305
- [ ] https://github.com/plone/Products.ATContentTypes/issues/28

after merge in this branch the sources must be changed back to the series branches

**Comment by gforcada** [comment]
I think that Products.ATCotnentTypes can be merged without the others being merged, it was already like that until I realized that... I will have a closer look at it.

**Comment by jensens** [comment]
this one was already in sync, so even if not merged

**Comment by gforcada** [comment]
@jensens it was in sync but not on buildout.coredev4 checkouts, so (maybe) it was broken. I'm adding P.ATCT it first without that backport and afterwards I will merge and we can see.

**Comment by gforcada** [comment]
@jensens no, it can not be merged alone: http://jenkins.plone.org/job/plone-4.3-python-2.7/1070/console

**Comment by gforcada** [comment]
I just merged some commits together and fixed some silly typos, let's see what jenkins says.

**Comment by jensens** [comment]
failed. 
@gforcada looks like jenkins does not report back?

**Comment by gforcada** [comment]
@jensens yeah, Jenkins is not really helpful here as Jenkins does not finish running the current script as soon as there is an error :-/ I will look into it later on.

**Comment by mauritsvanrees** [comment]
New try with Jenkins:
http://jenkins.plone.org/job/pull-request-5.0/876/

**Comment by mauritsvanrees** [comment]
Jenkins says:

```
Generated script '/home/jenkins/workspace/pull-request-5.0/bin/buildout'.
+ [ 1 = 1 ]
+ git checkout 4.3.x-csrffixes
error: Your local changes to the following files would be overwritten by checkout:
    core.cfg
Please, commit your changes or stash them before you can switch branches.
Aborting
Build step 'Execute shell' marked build as failure
```

Same error for #176.
But maybe pull requests are not working for this and this needs to be a plip job or something? I have not got the hang of that yet, sorry.

**Comment by gforcada** [comment]
That was me trying to make jobs less hard disk hungry.

I will fix in some hours.
El dia 13/02/2016 2:24, "Maurits van Rees" notifications@github.com va
escriure:

**Comment by mauritsvanrees** [comment]
This was superseded by #176 which has got most of the above and just got merged.

Should we want to go the all the way, updating plone.protect to 3.x in Plone 4.3, we can create a new pull request that can start by simply updating the plone.protect pin and source branch.

**Pull request closed without merging**
