### PR TITLE
[6.0] update dependency versions 

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM.
I have a doubt about updating `towncrier`, because there may be changes coming in that are not compatible with `zestreleaser.towncrier` or with our `pyproject.toml` files. But I can check this later when I do releases.

Fine to merge when green.

**Comment by jensens** [comment]
I can remove the towncrier ones - those can be handled later too.

**Pull request merged**
