### PR TITLE
Removed CMFDefault occurences

### PR DESCRIPTION
**Pull request by tomgross**
Need to merge first:
- [X] https://github.com/plone/plone.app.portlets/pull/51
- [X] https://github.com/plone/plone.app.contentrules/pull/13
- [X] https://github.com/plone/plone.app.multilingual/pull/164
- [X] https://github.com/plone/Products.PortalTransforms/pull/8
- [X] https://github.com/plone/plone.app.form/pull/12
- [x] https://github.com/plone/plone.app.testing/pull/13
- [X] https://github.com/plone/plone.app.upgrade/pull/32

### CODE REVIEW

**Comment by prakharjoshi** [comment]
@tomgross  Here is what I have been working on this helps removing the extra "<div>" tag in the beggining and end of the result. https://gist.github.com/prakharjoshi/16d593cee21801e0b91b . I have been working on to create a more appropriate script which passes more and more test cases. 
Also we can now remove SGMLParse and ScrubHTML classes as these classes have CMFDeault dependencies, right ?

**Comment by jensens** [comment]
Great work!
If merging, does it break if we do it one by one when keeping the above order? Or what is the best strategy?

**Comment by tisto** [comment]
@tomgross awesome! Can't wait to merge. :)

**Comment by tisto** [comment]
All pull requests have been merged except multilingual and testing. Both lead to test failures.

**Comment by tisto** [comment]
Multilingual pr test: http://jenkins.plone.org/job/pull-request/175/

**Comment by tisto** [comment]
Running the plip job: http://jenkins.plone.org/view/PLIPs/job/plip-noncmfdefault/7/

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.0/23/

**Comment by tomgross** [comment]
Superseded by https://github.com/plone/buildout.coredev/pull/90

**Pull request closed without merging**
