### PR TITLE
Set ROBOTSUITE_RETRY_COUNT = 3 in the bin/test environment.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This is a new feature from robotsuite.
Let's see how well this works.
It may not be right for all robot tests.
It can also be added to individual RobotSuiteTests with retry_count=X.
Note: with a retry count of 3, the test is tried 4 times.  One try, three retries.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Notes:

- We might want to do this only on Jenkins.
- And actually, maybe only on the Chrome tests, because the Firefox tests are pretty broken, where a retry does not help. We don't want the tests to take four times as long...

cc @gforcada to keep you in the loop.

**Comment by tisto** [comment]
@mauritsvanrees +1, we used to re-run our robot tests (before we moved to cypress) twice and this worked quite well for us. Can we then remove the "allowed failures" from Jenkins then? I find it highly misleading for devs when the build is green and some tests fail.

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
> Can we then remove the "allowed failures" from Jenkins then?

Maybe. Some failures have regressed into real failures that always fail. For example on Jenkins 5.1 I see a test for the [location query](https://jenkins.plone.org/job/plone-5.1-python-2.7-robot-chrome/178/robot/Robot/Test%20Querystring/Scenario%3A%20Location%20query/) that has failed the last 22 times (the entire shown build history).
On 5.2 there are actually no tests currently that are marked as unstable, although I have proposed to mark the 'add translation' test as [unstable](https://github.com/plone/plone.app.multilingual/pull/367). That may not be needed anymore with this change.

**Comment by mauritsvanrees** [comment]
Wait, we first must merge https://github.com/plone/buildout.coredev/pull/637 otherwise the current PR does nothing... I made the current PR after updating `robotsuite` to a different version which turned out to have problems, so I reverted it.

**Comment by mauritsvanrees** [comment]
Other PR has been merged.
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
All three PR jobs have timed out, which is maybe not too surprising.
Also, I see lots of exceptions from `plone.app.event` in the tests:

```
portlets - ERROR - Error while determining renderer availability of portlet ('context' '/plone' 'events'): can't subtract offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/cp37m/plone.portlets-2.3.1-py3.7.egg/plone/portlets/manager.py", line 119, in _lazyLoadPortlets
    isAvailable = renderer.available
  File "/home/jenkins/.buildout/eggs/cp37m/plone.app.event-3.2.6-py3.7.egg/plone/app/event/portlets/portlet_events.py", line 141, in available
    return self.data.count > 0 and len(self.events)
  File "/home/jenkins/.buildout/eggs/cp37m/plone.app.event-3.2.6-py3.7.egg/plone/app/event/portlets/portlet_events.py", line 189, in events
    expand=True, limit=data.count, **query
  File "/home/jenkins/.buildout/eggs/cp37m/plone.app.event-3.2.6-py3.7.egg/plone/app/event/base.py", line 163, in get_events
    sort_reverse)
  File "/home/jenkins/.buildout/eggs/cp37m/plone.app.event-3.2.6-py3.7.egg/plone/app/event/base.py", line 283, in expand_events
    IRecurrenceSupport(obj).occurrences(start, end)]
  File "/home/jenkins/.buildout/eggs/cp37m/plone.app.event-3.2.6-py3.7.egg/plone/app/event/base.py", line 282, in <listcomp>
    occurrences = [_obj_or_acc(occ, ret_mode) for occ in
  File "/home/jenkins/.buildout/eggs/cp37m/plone.app.event-3.2.6-py3.7.egg/plone/app/event/recurrence.py", line 77, in occurrences
    duration = event_end - event_start
TypeError: can't subtract offset-naive and offset-aware datetimes
```

I don't know if that is somehow caused by this PR. I have seen it before, but maybe that was on different tries of this same PR.

For the too often failing `plone.app.multilingual` tests, I have added a PR to [retry the tests](https://github.com/plone/plone.app.multilingual/pull/369) of only that package. That may be cleaner, although then we would need to do that in more packages. Ironically, the `plone.app.multilingual` tests seem to have stabilised...

**Comment by ale-rt** [comment]
It seems to me that we are retrying the whole scenario and just one test:
```
Test Controlpanel Security                                                    
==============================================================================
Scenario: Enable self registration in the Security Control Panel      | PASS |
------------------------------------------------------------------------------
Scenario: Enable users to select their own passwords in the Securi... | PASS |
------------------------------------------------------------------------------
Scenario: Enable user folders in the Security Control Panel           | PASS |
------------------------------------------------------------------------------
Scenario: Enable anyone to view 'about' information in the Securit... | PASS |
------------------------------------------------------------------------------
Scenario: Enable use email as login in the Security Control Panel     | PASS |
------------------------------------------------------------------------------
Scenario: Enable use uuid as uid in the Security Control Panel        | FAIL |
Keyword 'Input text and validate' failed after retrying for 30 seconds. The last error was: Element with locator 'form.widgets.username' not found.
------------------------------------------------------------------------------
Test Controlpanel Security                                            | FAIL |
6 critical tests, 5 passed, 1 failed
6 tests total, 5 passed, 1 failed
==============================================================================
Output:  /home/jenkins/workspace/pull-request-5.2-3.6/parts/test/test_controlpanel_security/Scenario_Enable_use_uuid_as_uid_in_the_Security_Control_Panel/output.xml

Retrying test "Scenario Enable use uuid as uid in the Security Control Panel (test_controlpanel_security.robot)" after failure. Retry 1.

==============================================================================
Test Controlpanel Security                                                    
==============================================================================
Scenario: Enable self registration in the Security Control Panel      | PASS |
------------------------------------------------------------------------------
Scenario: Enable users to select their own passwords in the Securi... | PASS |
------------------------------------------------------------------------------
Scenario: Enable user folders in the Security Control Panel           | FAIL |
Keyword 'Input text and validate' failed after retrying for 30 seconds. The last error was: Element with locator 'form.widgets.username' not found.
------------------------------------------------------------------------------
Scenario: Enable anyone to view 'about' information in the Securit... | FAIL |
Element 'id=workflow-transition-publish' not visible after 30 seconds.
------------------------------------------------------------------------------
Scenario: Enable use email as login in the Security Control Panel     | PASS |
------------------------------------------------------------------------------
Scenario: Enable use uuid as uid in the Security Control Panel        | FAIL |
Keyword 'Input text and validate' failed after retrying for 30 seconds. The last error was: Element with locator 'form.widgets.username' not found.
------------------------------------------------------------------------------
Test Controlpanel Security                                            | FAIL |
6 critical tests, 3 passed, 3 failed
6 tests total, 3 passed, 3 failed
```
If you check the robot log here https://jenkins.quaive.net/job/quaive-master-complete/1617/robot/report/robot_log.html#s1-s1-t69
You will see that only `Owner gets properly removed when user leaves workspace` is retried.

Retrying the whole scenario increases the chance of having issue related to the fact that the layer is not properly torn down after a failure.

I still need to investigate the difference between the original patch I reported on https://github.com/collective/robotsuite/issues/17 and what we have currently.

**Comment by tisto** [comment]
I don't know what this new robot command does. We used to re-run only the failing test on our CI. I can try to look up the old code we used if someone is interested...

**Comment by ale-rt** [comment]
Of course you are welcome :)

**Comment by mauritsvanrees** [comment]
Old PR by me, it never really worked out.
I am still interested in retrying tests, especially robot tests, but the current PR does not seem the best way.

In the future, we might want to switch to `pytest` and use https://github.com/pytest-dev/pytest-rerunfailures

**Comment by gforcada** [comment]
Or rather use [playwright](https://pypi.org/project/playwright/) which Asko told me there is an integration with robot framework 🎉

**Pull request closed without merging**
