### PR TITLE
Upgrade to Zope 4.4.5

### PR DESCRIPTION
**Pull request by vincentfretin**
Don't merge, I want to run the tests.

### CODE REVIEW

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
Plone Jenkins CI - pull-request-5.2
`plone.restapi.tests.test_services_querystringsearch.TestQuerystringSearchEndpoint.test_querystringsearch_do_not_return_context`

```
u'http://localhost:44923/plone/testdocument2' != 'http://localhost:55001/plone/testdocument2'

  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jenkins/workspace/pull-request-5.2/src/plone.restapi/src/plone/restapi/tests/test_services_querystringsearch.py", line 168, in test_querystringsearch_do_not_return_context
    "http://localhost:55001/plone/testdocument2",
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
```

It seems we have a random port now instead of hard coded 55001?

**Comment by vincentfretin** [comment]
@tisto Can you please make a fix for this test in plone.restapi to not hard code the port?

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
I started https://github.com/plone/buildout.coredev/pull/664 cause I did not see this one, feel free to close it if you already have ongoing work!

**Comment by ale-rt** [comment]
Aniway I think #664 will fail for the same reason this one is failing...

**Comment by ale-rt** [comment]
The error should be fixed by: https://github.com/plone/plone.restapi/pull/979
No wonder all the builds are failing :)

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
Thanks @ale-rt

**Pull request closed without merging**
