### PR TITLE
New PLIP process

### PR DESCRIPTION
**Pull request by thet**
This updates the buildout.coredev documentation and changes references to dev.plone.org to GitHub. This is done in preparation of the upcoming "Call for PLIPs".

Things related and open to do:
- [x] Additional review of the plips.rst doc and this pull-request.
- [x] Approve https://github.com/plone/plone.api/blob/master/docs/contribute/conventions.rst and move it to a more appropriate place (possibly replacing https://github.com/plone/buildout.coredev/blob/5.0/docs/style.rst). Update the link in this pull-request.
- [x] Instead of the tag `03 type: feature` rename to `03 type: feature (plip)`.

plone.org should also be updated with regarding docs mentioning the PLIP process. See:
- [ ] https://github.com/plone/Products.CMFPlone/issues/1286

Related docs.plone.org issues:
- [x] https://github.com/plone/documentation/issues/467
- [x] https://github.com/plone/documentation/issues/468
- [x] https://github.com/plone/documentation/issues/469
- [ ] https://github.com/plone/documentation/issues/470

I'd love to have these issues resolved before doing the "Call for PLIPs".

/cc @plone/framework-team @plone/documentation-team 

Updates:
- label renaming updated, see comment 1 below -- @jensens

### CODE REVIEW

**Comment by jensens** [comment]
> Instead of the tag "03 type: feature" add "05 type: PLIP" (not every feature might be a PLIP) or replace the feature one and say instead PLIP.

I disagree. First this is one tag to much here and it increases confusion. 
Also every feature (new thing) is a PLIP, all others are enhancements of existing.

A little history: before plone conference 2015 I had `03 type: plip`. At conference sprint I discussed in person witha bunch of people. After that we decided to rename to `03 type: feature` because PLIP is an abbreviation specific to Plone, so non-Plone people might not know what its meant to be. 

I normally like short tags. But in this case - and to avoid confusion - I propose to rename it to the more clumpsy 

**03 type: feature (plip)**

I can do this. I already wrote the scripts to automate this.

**Comment by thet** [comment]
tnx @jensens 
+1 for your suggestion to change to "03 type: feature (plip)" (and not having an additional PLIP tag).
since our our feature improvement process is named "PLIP", this tag makes it absolutely clear for Plone devs and newbies get the chance to learn our wording (which is also important).

**Comment by thet** [comment]
IMO, ready to be merged.

**Comment by jensens** [comment]
looks fine

**Comment by ebrehault** [comment]
Sorry @thet, I have been busy, I have just reviewed it now. Looks good to me.

**Pull request merged**
