### PR TITLE
Use Zope 4.0 final

### PR DESCRIPTION
**Pull request by jensens**
yes!

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
Some of the failing tests fail since https://github.com/zopefoundation/Zope/commit/b4495eb403c6:

* plone.dexterity.tests.test_webdav.TestFolderDataResource.test_PROPPATCH 
* plone/app/testing/layers_zserver.rst
* plone/testing/zserver.rst
* Products/Archetypes/tests/traversal.txt
* Products/ATContentTypes/tests/traversal.txt
* Products.ATContentTypes.tests.test_atnewsitem.TestATNewsItemFunctional.test_createObject

I don't know about the others.

**Comment by pbauer** [comment]
Here's how to run only the faling tests for debugging (python 2.7 only):

```
./bin/test -s Products.ATContentTypes -t test_createObject -t traversal.txt -s Products.Archetypes -t traversal.txt -s plone.app.testing -t layers_zserver.rst -s plone.testing -t zserver.rst -s plone.dexterity -t test_PROPPATCH -s Products.CMFPlone -t testPUTIndexHtml -t testPUTIndexHtmlIntoPortal  -t testPUTDocument   -t testPUTDocumentIntoPortal -t testPUTIndexHtmlDocument -t testPUTIndexHtmlDocumentIntoPortal    -s Products.CMFEditions -t webdav_history.rst   -s plone.app.contenttypes -t test_file_put_rfc822 -t test_image_put_rfc822
```

**Comment by pbauer** [comment]
All but one failing test are fixes with https://github.com/zopefoundation/Zope/pull/624.

**Comment by pbauer** [comment]
The last failing test is `Products.ATContentTypes.tests.test_atnewsitem.TestATNewsItemFunctional.test_createObject` and is caused by a change in `ZPublisher.HTTPResponse.redirect` with https://github.com/zopefoundation/Zope/commit/ca445a661d3992352f76266009798c9305d834db#diff-80f3a2c3ed7611b843ad03eda4878084R218

The problem is that the location is changed from

    http://nohost/plone/Members/test_user_1_/portal_factory/News Item/news_item.2019-05-13.5570404352/

to

    http://nohost/plone/Members/test_user_1_/portal_factory/News%20Item/news_item.2019-05-13.5570404352/

which results in a 404.

**Comment by pbauer** [comment]
The lasts failing test with Zope 4.0 are now fixed with https://github.com/plone/Products.ATContentTypes/pull/63 (merged) and https://github.com/zopefoundation/Zope/pull/624 (not yet merged). See https://github.com/plone/buildout.coredev/pull/582 for a buildout that contains this.

**Comment by pbauer** [comment]
Replaces by https://github.com/plone/buildout.coredev/pull/589

**Pull request closed without merging**
