### PR TITLE
Use robotframework 5.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Update all related packages to the latest, for example Selenium.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
It was already green, but there was a conflict in `versions.cfg`. Let's try again:

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Green again!

One thing to note though, is that Robotframework 5 has no concept anymore of critical versus non-critical tests. [See the docs](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#migrating-from-criticality-to-skip). `robotsuite` can still handle this for us, see [code](https://github.com/collective/robotsuite/blob/98f7b50b240b6d7890ba8ce83b67752d970c4c16/src/robotsuite/__init__.py#L410), though we don't currently use this feature in Plone 6.
So Jenkins currently says that there were zero critical tests. Compare [original](https://jenkins.plone.org/job/pull-request-6.0-3.9/1180/) versus [new](https://jenkins.plone.org/job/pull-request-6.0-3.9/1179/).

This might need a change somewhere in Jenkins, to no longer display the numbers for critical tests.
cc @gforcada @fredvd 

Regardless, I would say: ready for merge.

**Comment by gforcada** [comment]
I guess this is table you refer to comes directly from robot framework plugin for jenkins 🤔

**Pull request merged**
