### PR TITLE
Update to latest z3c.form

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@plone/testing-team I think there's something broken with buildout.coredev jenkins intetration ... could this be? I geht this, when starting this PR manually on jenkins: https://jenkins.plone.org/job/pull-request-6.0-3.7/1029/console

**Comment by mauritsvanrees** [comment]
It is because some jobs use the unauthenticated git protocol, which has been disabled on GitHub since this week.
I have opened PRs:

- https://github.com/plone/mr.roboto/pull/92
- https://github.com/plone/jenkins.plone.org/pull/293

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
ok ... let's check +195 new failures 🙈

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Down to 13 failing tests. Progress!

**Comment by petschki** [comment]
Right now I'm fixing test issues comming from the new `OrderedDict` implementation of `z3c.form.field.Fields` ... this should be done quickly ... I'll try to reimplement the missing `z3c.form.object.ObjectSubForm` afterwards ...

**Comment by petschki** [comment]
@mauritsvanrees I've set up a plip config here https://github.com/plone/buildout.coredev/blob/petschki/z3c-form-4/plips/plip-3459-z3c-form-latest.cfg ... could this be installed as a separate jenkins job? then I do not have to fiddle around with the `checkouts.cfg` and `sources.cfg` of coredev ...

**Comment by mauritsvanrees** [comment]
That would be something for the admins team.
@fredvd @gforcada Could one of you set up pip jobs for this please?

@petschki You would first need to copy your PLIP config to the 6.0 branch though.

**Comment by petschki** [comment]
@fredvd @gforcada I've created the config for plip-3459 in the 6.0 branch ... would be great to have a plip job in jenkins since there are some moving targets there

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
6 failing tests remaining ...

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
@petschki thanks for your efforts on bringing newer z3c.form! I will try to set up the jenkins jobs within today, sorry, I'm a bit busy right now 😅

**Comment by petschki** [comment]
@gforcada no problem. I've talked to @fredvd and we decided that this PR is enough to get the packages tested. So this needs no plip job anymore.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — COMMENTED** [review]
Given tests are green and branches are merged, +1000 to merge this one

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by fredvd** [comment]
Woohoo, great work @petschki !!

**Comment by mauritsvanrees** [comment]
Great!

**Pull request merged**
