### PR TITLE
Update 5.0 to latest zope 2.13.23

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/185/

**Comment by jensens** [comment]
Ok, this fails with datetime and timezone problems. Things one would not expect....

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/216/

**Comment by jensens** [comment]
jenkins was red, next trial http://jenkins.plone.org/job/pull-request-5.0/218/

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/220/

**Comment by mauritsvanrees** [comment]
Mostly test failures about dates. Could be due to updated DateTime module, but I have not checked.

For ease of reference, here is the diff between the current and new Zope2 versions:

```
$ diff zope-2-13-22-versions.cfg zope-2-13-23-versions.cfg 
0a1,2
> #  Compiled from http://download.zope.org/Zope2/index/2.13.23/versions.cfg
> 
6,7c8
< # Zope2-specific
< Zope2 = 2.13.22
---
> Zope2 = 2.13.23
9,10c10,11
< Acquisition = 2.13.8
< DateTime = 2.12.7
---
> Acquisition = 2.13.9
> DateTime = 2.12.8
18,20c19,21
< Products.BTreeFolder2 = 2.13.4
< Products.ExternalMethod = 2.13.0
< Products.MailHost = 2.13.1
---
> Products.BTreeFolder2 = 2.13.5
> Products.ExternalMethod = 2.13.1
> Products.MailHost = 2.13.2
24c25
< Products.StandardCacheManagers = 2.13.0
---
> Products.StandardCacheManagers = 2.13.1
30c31
< zLOG = 2.11.1
---
> zLOG = 2.11.2
33,38d33
< # ZTK KGS overrides
< manuel = 1.1.1
< mechanize = 0.2.5
< python-gettext = 1.2
< ZConfig = 2.9.1
< ZODB3 = 3.10.5
40a36,39
> ZConfig = 2.9.3
> ZODB3 = 3.10.5
> mechanize = 0.2.5
> pytz = 2015.4
44c43
< zope.testbrowser = 3.11.1
---
> 
```

**Comment by esteele** [comment]
I had to build that kgs from hand since the release on zope.org changed formats and left a lot of things out. I'd appreciate it if someone could sanity check that for me to make sure I didn't muck it up even more.

**Comment by pbauer** [comment]
Here are the few versions that actually change with this pr (above: old, below: new).
The test-failures are most likely due to the bump of pytz from 2013b to 2015.4. These updates do not contain any code-changes but only updated timezone-databases (see https://launchpad.net/pytz/+announcements). This means we'll have to update the new dates/timezones in the failing tests.

```
Acquisition-2.13.8
Acquisition-2.13.9

Products.ExternalMethod-2.13.0
Products.ExternalMethod-2.13.1

Products.MailHost-2.13.1
Products.MailHost-2.13.2

ZConfig-2.9.1
ZConfig-2.9.3

Zope2-2.13.22
Zope2-2.13.23

manuel-1.1.1
manuel-1.8.0

python_gettext-1.2
python_gettext-1.0

pytz-2013b
pytz-2015.4

zLOG-2.11.1
zLOG-2.11.2

zope.testrunner-4.4.4
zope.testrunner-4.4.9
```

**Comment by mauritsvanrees** [comment]
This looks hard to get right. It will currently fail, but let's give Jenkins another go at it:
http://jenkins.plone.org/job/pull-request-5.0/238/

**Comment by mauritsvanrees** [comment]
Lots of funky stuff. plone.app.event tests fail because the list of occurrences of an event is supposed to have the event as first item, but this is not the case because timezones mess up the logic. When you jump in with a pdb, you get things like this In plone.event.recurrence:

```
(Pdb++) start.tzinfo
<DstTzInfo 'Europe/Vienna' LMT+1:05:00 STD>
(Pdb++) start = pydt(start, exact=False)  # from plone.event.utils
(Pdb++) start.tzinfo
<DstTzInfo 'Europe/Vienna' CET+1:00:00 STD>
```

The LMT+1 is how the new pytz wants it, CET+1 is like the old pytz, and Zope DateTime prefers GMT+1. All three somehow need to work together and be comparable, which is hard. It probably gets harder if you want to try to support both the old and new pytz versions with the same code base, if that is a goal.

It also does not help if `bin/test -s plone.dexterity` (with a fix on master) runs fine and `bin/test -s plone.dexterity -D` gives an error:

```
Error in test test_item_notifyModified (plone.dexterity.tests.test_content.TestContent)
Traceback (most recent call last):
  File "/Users/mauritsvanrees/buildout/python2.7/parts/opt/lib/python2.7/unittest/case.py", line 400, in debug
    getattr(self, self._testMethodName)()
  File "/Users/mauritsvanrees/shared-eggs/mocker-1.1.1-py2.7.egg/mocker.py", line 149, in test_method_wrapper
    result = test_method()
  File "/Users/mauritsvanrees/community/plone-coredev/5.0/src/plone.dexterity/plone/dexterity/tests/test_content.py", line 785, in test_item_notifyModified
    self.assertNotEqual(i.modification_date, i.creation_date)
  File "/Users/mauritsvanrees/buildout/python2.7/parts/opt/lib/python2.7/unittest/case.py", line 524, in assertNotEqual
    raise self.failureException(msg)
AssertionError: DateTime('2014/06/01 00:00:00 GMT+2') == DateTime('2014/06/01 00:00:00 GMT+2')
```

In this case, somehow one of the other tests does not properly cleanup a mock DateTime, so any DateTime call results in the same date. Strange that the debug flag for bin/test would cause that.

Also, if we update pytz, I wonder if we want to update Zope DateTime too, from 3.0.3 to 4.0.1. But that does not help for the tests, at least not for all of them.

Meanwhile, Jenkins gives strange errors in plone.app.testing, so let's try again:
http://jenkins.plone.org/job/pull-request-5.0/239

For now, if we want to use the latest Zope2, I guess it it better to override its pytz version and keep that to  the 2013b version that we have been using so far.  Or update it to 2014.2 at the most.

**Comment by mauritsvanrees** [comment]
And trying again, after fixing a syntax error in the Japanese po file which tripped up the tests...
http://jenkins.plone.org/job/pull-request-5.0/240/

**Comment by mauritsvanrees** [comment]
Jenkins is still running, but it is failing already.

So let's see what happens when we use a less new pytz version:
http://jenkins.plone.org/job/pull-request-5.0/241/

**Comment by mauritsvanrees** [comment]
Trying yet again, with the original pytz 2013b:
http://jenkins.plone.org/job/pull-request-5.0/243/

**Comment by mauritsvanrees** [comment]
Jenkins is still not happy.
I did a rebase and a forced push, which helped a bit in the related pull request for 4.3. Sorry if this breaks anything for you locally.
Next try: http://jenkins.plone.org/job/pull-request-5.0/244/

**Comment by mauritsvanrees** [comment]
Still failing.  Reverting zope.testrunner to an earlier version helped for pull request #100, so let's try that here too. Go Jenkins:
http://jenkins.plone.org/job/pull-request-5.0/245/

**Comment by mauritsvanrees** [comment]
Hah, now the tests pass, except for one: "Scenario Show warning when deleting linked item from foldercontents". That is the randomly failing linkintegrity test from https://github.com/plone/Products.CMFPlone/issues/854.
So: seems ready for review then.
Updating zope.testrunner and/or pytz and/or DateTime may be something for a separate pull request.

**Comment by esteele** [comment]
Awesome. Thanks!

**Comment by jensens** [comment]
rebased, tests: http://jenkins.plone.org/job/pull-request-5.0/274/

**Comment by pbauer** [comment]
Rebased. test: http://jenkins.plone.org/job/pull-request-5.0/302/

**Comment by jensens** [comment]
:+1:

**Pull request merged**
