### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fix contributor's agreement
link.

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
I've repeated the PR with reference to #412(for branch 5.2) . You can review my PR as soon as the Jenkins build test is successful.

**Comment by gforcada** [comment]
@mrsaicharan1 thanks for porting your patch!

note that `plone.org` is missing inside the backticks:

    `plone.org <http://xxxx>`_

Would you mind to update it?

**Comment by mrsaicharan1** [comment]
Done! Made the changes in a new PR #414 . Will close this PR with unmerged commits .

**Comment by gforcada** [comment]
@mrsaicharan1 you don't need to create more pull requests, just amend the commits and push on the same branch, git can do that and much much more 😉 

As I merged the other, this can be closed.

**Pull request closed without merging**
