### PR TITLE
Use zope 5.2.1

### PR DESCRIPTION
**Pull request by jensens**
see https://github.com/plone/Products.CMFPlone/issues/3274

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
I think you meant this PR to go to 6.0 instead of 5.2. :-) Ah, you just fixed that.

LGTM.
I think some tests will fail on 6.0 because Zope has become stricter in the whole bobo aware zope traverse business. Especially I think CMFEditions tests will fail. But let's see.
If there are too many failures, we should take the hotfix code from `expressions.py` and put it in CMFPlone.

**Comment by jensens** [comment]
Python 3.9 fails with our ancient Pillow. No idea why now. But given this Matrix we need to upgrade:
Screenshot from 2021-06-23 16-02-15 
from https://pillow.readthedocs.io/en/latest/installation.html

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
A bunch of test failures.
@mauritsvanrees do we need the Hotfix in here to make it work and allow certain stuff?

**Comment by mauritsvanrees** [comment]
> A bunch of test failures.
> @mauritsvanrees do we need the Hotfix in here to make it work and allow certain stuff?

I feared this. Yes, adding the hotfix, particularly the `expressions.py` part, should help. There might be unrelated issues.
It would be good if we do not need the hotfix, and just use the stricter security checks in Plone 6. But for the moment it should be fine.

Let me paste the 13 failing tests, so we know which packages to look at later:

```
Products.CMFEditions.tests.test_versions_history_form.TestVersionsHistoryForm.test_versions_history_form
Products.CMFEditions.tests.test_versions_history_form.TestVersionsHistoryForm.test_versions_history_form_custom_version_view
Products.CMFPlone.tests.testSecurity.TestFunctional.test_hotfix_20160419
Products.CMFPlone.tests.testSecurity.TestFunctional.test_plonetool
five.customerize.zpt.txt
plone.app.customerize.tests.testBrowserLayers.txt
plone.app.users.tests.password.rst
plone.app.users.tests.personal_preferences.rst
plone.app.users.tests.userdata.rst
plone.app.versioningbehavior.tests.doctest_behavior.txt
plone.contentrules.README.rst
src.Products.PlonePAS.tests.cookie_auth.rst
plone.app.versioningbehavior.tests.test_functional.FunctionalTestCase.test_versions_history_form_should_work_with_dexterity_content
```

**Comment by mauritsvanrees** [comment]
Products.CMPlone meanwhile has a patch.
I have rebased the coredev branch, and added a pin for the old `zope.component 4.6.2`. Version 5.0.0 gives mostly the same problems as in [Plone 5.2 with Zope 4.6.2](https://github.com/plone/buildout.coredev/pull/725#issuecomment-872272811).

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
It is green. Well, one known unstable robot test (thememapper LESS builder) on Python 3.9.
I merge.

**Pull request merged**
