### PR TITLE
Demonstration of possible approach for Zope allowed_attributes

### PR DESCRIPTION
**Pull request by MatthewWilkes**
This is a draft PR, I'm just trying to convince jenkins to build the branch so we can talk about it.

### CODE REVIEW

**Comment by MatthewWilkes** [comment]
@pbauer Your test is at https://jenkins.plone.org/job/pull-request-5.2-3.7/215/testReport/plone.app.event.tests.test_ical_import/

**Comment by pbauer** [comment]
@MatthewWilkes The Python 2.7 the job fails with: 

```
Error in test test_enable_ical_import (plone.app.event.tests.test_ical_import.TestICALImportSettings)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 398, in debug
    getattr(self, self._testMethodName)()
  File "/Users/pbauer/workspace/coredev/src/plone.app.event/plone/app/event/tests/test_ical_import.py", line 58, in test_enable_ical_import
    self.browser.open(f1_url + '/ical_import_settings/enable')
  File "/Users/pbauer/.cache/buildout/eggs/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 251, in open
    self._processRequest(url, make_request)
  File "/Users/pbauer/.cache/buildout/eggs/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 275, in _processRequest
    resp = make_request(reqargs)
  File "/Users/pbauer/.cache/buildout/eggs/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 249, in make_request
    return self.testapp.get(url, **args)
  File "/Users/pbauer/.cache/buildout/eggs/WebTest-2.0.33-py2.7.egg/webtest/app.py", line 335, in get
    expect_errors=expect_errors)
  File "/Users/pbauer/.cache/buildout/eggs/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 94, in do_request
    expect_errors)
  File "/Users/pbauer/.cache/buildout/eggs/WebTest-2.0.33-py2.7.egg/webtest/app.py", line 628, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/Users/pbauer/.cache/buildout/eggs/WebOb-1.8.5-py2.7.egg/webob/request.py", line 1310, in send
    application, catch_exc_info=True)
  File "/Users/pbauer/.cache/buildout/eggs/WebOb-1.8.5-py2.7.egg/webob/request.py", line 1278, in call_application
    app_iter = application(self.environ, start_response)
  File "/Users/pbauer/.cache/buildout/eggs/WebTest-2.0.33-py2.7.egg/webtest/lint.py", line 201, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/Users/pbauer/.cache/buildout/eggs/plone.testing-7.0.1-py2.7.egg/plone/testing/_z2_testbrowser.py", line 38, in wrapped_func
    return func(*args, **kw)
  File "/Users/pbauer/.cache/buildout/eggs/plone.testing-7.0.1-py2.7.egg/plone/testing/_z2_testbrowser.py", line 65, in __call__
    wsgi_result = publish(environ, start_response)
  File "/Users/pbauer/workspace/coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 337, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/pbauer/workspace/coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 255, in publish
    bind=1)
  File "/Users/pbauer/workspace/coredev/src/Zope/src/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/Users/pbauer/workspace/coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 61, in call_object
    return obj(*args)
TypeError: unbound method __call__() must be called with simple instance as first argument (got nothing instead)
```

The same happens when I try enabling ical-import in a instance in Python 2.7:

```
2019-05-28 09:34:53 ERROR Zope.SiteErrorLog 1559028893.980.498082859497 http://localhost:8080/Plone4/ad/@@ical_import_settings/enable
Traceback (innermost last):
  Module ZServer.ZPublisher.Publish, line 144, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZServer.ZPublisher.Publish, line 44, in call_object
TypeError: unbound method __call__() must be called with simple instance as first argument (got nothing instead)
```
In Python 3.6 and 3.7 it works and all test are green.

**Comment by MatthewWilkes** [comment]
Looks like a potential intermittent failure on -3.6?

**Comment by MatthewWilkes** [comment]
I re-ran the 3.6 build that failed due to a port collision and it worked.

**Comment by MatthewWilkes** [comment]
I've done some re-architecting of this to avoid the `setattr`s. It makes it a more involved change, but less magic. I'm running the tests again to see if I broke things in there.

**Comment by pbauer** [comment]
replaced by https://github.com/plone/buildout.coredev/pull/589

**Pull request closed without merging**
