### PR TITLE
Update build tools

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by jensens** [comment]
Latest zc.buildout is today 2.11.0 https://pypi.python.org/pypi/zc.buildout/2.11.0
@ale-rt Any reason to not use it?

**Comment by ale-rt** [comment]
I'd love! When I submitted this PR I wanted to test the latest setuptools and zc.buildout.
Of course the version I pinned are already outdated.

Unfortunately the job setup seems to switch to this branch after the requirements are installed:
```
+ pip install -r requirements.txt
...
Successfully installed setuptools-33.1.1 zc.buildout-2.9.5
...
Switched to a new branch 'update-build-tools-52'
Branch update-build-tools-52 set up to track remote branch update-build-tools-52 from origin.
+ buildout -c jenkins.cfg
Getting distribution for 'zc.buildout==2.10.0'.
...
VersionConflict: (zc.buildout 2.9.5 (/home/jenkins/shiningpanda/jobs/86a760ac/virtualenvs/0dd3bfc1/lib/python2.7/site-packages), Requirement.parse('zc.buildout==2.10.0'))
Build step 'Virtualenv Builder' marked build as failure
```

I think the job should first switch the branch and then run pip install -r requirements.txt.

CC: @gforcada

**Comment by gforcada** [comment]
@ale-rt good point. This is the script that is run on the pull requests jobs: https://github.com/plone/jenkins.plone.org/blob/master/jobs/scripts/pr-tests.sh I would gladly review a pull request for it :-) Or I will do that myself if no one beats me on that.

**Comment by ale-rt** [comment]
@gforcada: https://github.com/plone/jenkins.plone.org/pull/217

**Comment by gforcada** [comment]
@ale-rt I finished deploying the jobs with the new configuration, thanks again for the pull request!, give them a try whenever you want 😉

**Pull request merged**
