### PR TITLE
Fix tests against `Products.GenericSetup >= 2.0`.

### PR DESCRIPTION
**Pull request by icemac**
Using the branches which contain the fixes.

### CODE REVIEW

**Comment by ale-rt** [comment]
Will probably check this tonite!

**Comment by ale-rt** [comment]
For the moment we have stil the following failing tests:
```
plone.app.viewletmanager.tests.test_exportimport.ViewletSettingsStorageXMLAdapterTests.test_body_get
plone.app.viewletmanager.tests.test_exportimport.ViewletSettingsStorageXMLAdapterTests.test_body_set
Products.CMFPlone.exportimport.tests.testControlPanel.ControlPanelXMLAdapterTests.test_body_get
Products.CMFPlone.exportimport.tests.testControlPanel.ControlPanelXMLAdapterTests.test_body_set
Products.CMFPlone.exportimport.tests.testPropertiesTool.PropertiesToolXMLAdapterTests.test_body_get
Products.CMFPlone.exportimport.tests.testPropertiesTool.PropertiesToolXMLAdapterTests.test_body_set
Products.CMFPlone.exportimport.tests.testPropertiesTool.PropertySheetXMLAdapterTests.test_body_get
Products.CMFPlone.exportimport.tests.testPropertiesTool.PropertySheetXMLAdapterTests.test_body_set
Products.CMFPlacefulWorkflow.tests.exportimport.txt
plone.app.workflow.tests.test_exportimport.TestExport.test_export_empty
plone.app.workflow.tests.test_exportimport.TestExport.test_export_multiple
```

**Comment by ale-rt** [comment]
I am trying to port plone.app.viewletmanager now

**Comment by mauritsvanrees** [comment]
I have merged the PRs for plone.app.contentrules and plone.app.portlets. So the `GenericSetup-2.0` branch is no longer needed for them.
Are the changes to the plone.testing and plone.app.testing branches still relevant?

**Comment by ale-rt** [comment]
plone.app.viewletmanager tests fixed.
@mauritsvanrees I suspect we will have problems with the build now that those two plone.app.* branches are merged.

**Comment by mauritsvanrees** [comment]
@ale-rt I expressly did not yet remove the PR branches in this case, so I think it should be okay.

**Comment by ale-rt** [comment]
I think plone.app.workflow tests are fixed by this branch https://github.com/plone/plone.app.workflow/tree/python3 from @jessesnyder 
I am adding the branch to the sources.cfg

**Comment by ale-rt** [comment]
I think we should also use the python3 branch of  Products.CMFPlone, @icemac.

**Comment by ale-rt** [comment]
Now only the following tests are failing: 
```
Products.CMFPlone.exportimport.tests.testControlPanel.ControlPanelXMLAdapterTests.test_body_get
Products.CMFPlone.exportimport.tests.testControlPanel.ControlPanelXMLAdapterTests.test_body_set
Products.CMFPlone.exportimport.tests.testPropertiesTool.PropertiesToolXMLAdapterTests.test_body_get
Products.CMFPlone.exportimport.tests.testPropertiesTool.PropertiesToolXMLAdapterTests.test_body_set
Products.CMFPlone.exportimport.tests.testPropertiesTool.PropertySheetXMLAdapterTests.test_body_get
Products.CMFPlone.exportimport.tests.testPropertiesTool.PropertySheetXMLAdapterTests.test_body_set
Products.CMFPlacefulWorkflow.tests.exportimport.txt
```

**Comment by icemac** [comment]
@ale-rt I do not like to use the `py3` branch of `CMFPlone` as these changes should be merged in a short timeframe to get coredev buildout green again. (same for `plone.app.workflow`)

I am going to fix the remaining failures by now.

**Comment by ale-rt** [comment]
Ok! I see your point and I agree :)

**Comment by ale-rt** [comment]
@icemac merged :)

**Pull request merged**
