### PR TITLE
robotsuite = 2.2.1 [5.2]

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This has the retry_count feature, without the breaking robotframework changes.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]

**Review by tisto — APPROVED** [review]

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
This can be merged anyway right?
I do not see any problem in doing that even if we are not using the new retry feature.

**Comment by mauritsvanrees** [comment]
Yes, can be merged. I think one job was failing, and I restarted it this morning, and is green now.

**Pull request merged**
