### PR TITLE
Change heading to be less specific

### PR DESCRIPTION
**Pull request by jean**
I was looking at the docs wondering "how do I get started"?
I don't want to commit fixes to the core, I just want to trial a bleeding edge Plone, and the original heading was opaque to me.

### CODE REVIEW

**Comment by jensens** [comment]
- your change is on the 4.3 branch only
- the text below the heading may need some chnages too, so it reflects the different targets.

**Comment by jean** [comment]
It's on 4.3 because that is current stable and there's no _master_ branch. What branch should I commit on so that future release branches will get the change?

**Comment by jensens** [comment]
future plone 5.0 is on the 5.0 branch

**Comment by jean** [comment]
https://github.com/plone/buildout.coredev/pull/53 for 5.0 branch

**Pull request merged**
