### PR TITLE
implement plip 1653 - restructure static resources

### PR DESCRIPTION
**Pull request by thet**
Implementation of https://github.com/plone/Products.CMFPlone/issues/1653

Depends on:
- https://github.com/plone/buildout.coredev/pull/518
- https://github.com/plone/Products.CMFPlone/pull/2542
- https://github.com/plone/mockup/pull/874
- https://github.com/plone/plone.app.theming/pull/149
- https://github.com/plone/plone.resourceeditor/pull/22
- https://github.com/plone/plone.staticresources

### CODE REVIEW

**Comment by gforcada** [comment]
@thet is the PLIP job not enough to test things out? As I see that you are using the 5.2 pull request jenkins job... just wondering :smile:

**Comment by jensens** [comment]
what is the state of this PR? may you apply the labels please @thet

**Comment by thet** [comment]
@gforcada oh tnx! I missed that you already created the PLIP job.

@jensens  done.

**Comment by jensens** [comment]
@thet, why did you close it?

**Pull request closed without merging**
