### PR TITLE
try Zope 4.0b6 with newest ZODB before release

### PR DESCRIPTION
**Pull request by pbauer**
Test the fix for https://github.com/zopefoundation/ZODB/issues/208.

Do not merge! This simply tests if updating to released versions with the fix will work for Plone.

### CODE REVIEW

**Comment by pbauer** [comment]
@gforcada the jobs https://jenkins.plone.org/job/pull-request-5.2-3.6/2 and https://jenkins.plone.org/job/pull-request-5.2-3.7/3 did not pick up the new checkouts of ZODB and transaction. The one for 2.7 did. The jobs seem to be not properly configured.

The failure is a different issue though.

**Comment by pbauer** [comment]
The fix requires additional changes to Zope (See https://github.com/zopefoundation/ZODB/issues/208#issuecomment-430627634)

**Comment by gforcada** [comment]
@pbauer I will have a look

**Comment by gforcada** [comment]
@pbauer fixed! pull request jobs are running already :smiley:

**Comment by pbauer** [comment]
these checkouts are now all merged

**Pull request closed without merging**
