### PR TITLE
Prepare for new icalendar release

### PR DESCRIPTION
**Pull request by mauritsvanrees**
I want to see if anything breaks before a new icalendar release is out. See https://github.com/collective/icalendar/issues/429

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
The tests were green (except some gh-actions that already fail on the 6.0 branch), so a new `icalendar` release would pose no problem.

I have updated the branch and force pushed the changes. We no longer checkout `icalendar`, but we do already add a backports pin for Python 3.8 for a new dependency. And I have removed `icalendar` from `tests.cfg` because they need to be run with `pytest` and the repo has gh-actions set up, so core Plone does not need to do that. `icalendar` is more independent now.

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I have rebased and force pushed. Meanwhile icalendar 5.0.0 has really been released, so I have added this pin.

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
All green, ready for merge.

**Review by ale-rt — APPROVED** [review]

**Pull request merged**
