### PR TITLE
Fix PLIP base config to work with new WSGI config.

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Comment by davisagli** [comment]
Note that this should become unnecessary if my changes in https://github.com/plone/plone.recipe.zope2instance/pull/52 get merged.

**Comment by agitator** [comment]
shouldn't plipbase.cfg extend from buildout-py2.cfg or buildout-py3.cfg?

**Comment by thet** [comment]
@agitator - @gforcada is working on a solution on that. see: https://github.com/plone/buildout.coredev/issues/549

**Comment by jensens** [comment]
I think it does not hurt if we merge, even if it becomes obsolete soon.

**Pull request merged**
