### PR TITLE
Add plone.api to plone_app_testing alltests group.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.0/280/

**Comment by tisto** [comment]
@jaroel looks like adding plone.api to the plone_app_testing alltests group causes some serious test isolation issues:

http://jenkins.plone.org/job/pull-request-5.0/280/consoleFull

**Comment by jaroel** [comment]
Yay.

**Comment by jensens** [comment]
This Pull Request has stalled for a while now and is closed. If you care about this Pull Request please reopen at any time.

**Pull request closed without merging**
