### PR TITLE
Update sources.cfg, versions.cfg

### PR DESCRIPTION
**Pull request by thet**
Sources.cfg:
- Use Products.ZCatalog 3.0.x branch
- Remove collective.elephantvocabulary
- Remove collective.js.jqueryui
- Use zope.globalrequest 1.2.x branch

versions.cfg:
- Remove collective.elephantvocabulary

The changes with Products.ZCatalog and zope.globalrequest are necessary to allow buildout to run with `auto-checkout = *`

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Actually, collective.elephantvocabulary should not be removed: plone.app.event still uses it. Are you planning to remove it from there?

**Comment by gforcada** [comment]
@mauritsvanrees the dependency on plone.app.event is gone thanks to @davisagli :-) though not released

**Comment by mauritsvanrees** [comment]
But... it is still being pulled in. At the end of a buildout run I get:

```
The following part definition lists the versions picked:
[versions]
collective.elephantvocabulary = 0.2.5
```

Ah, it is still used in `tests.cfg`. I will remove it from there.

**Comment by thet** [comment]
Thans @mauritsvanrees for checking that!

**Pull request merged**
