### PR TITLE
Bump bootstrap/setuptools on 5.0

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Same as #209.

The Jenkins jobs need a manual fix though, so I'll wait with testing.

### CODE REVIEW

**Comment by gforcada** [comment]
It can be tested and merged anytime, thanks for backporting

**Comment by mauritsvanrees** [comment]
I see you handled this in #211 already so I'll close this one.
All seems to be fine now. Thanks for your quick help!

**Comment by gforcada** [comment]
@mauritsvanrees sorry we were stepping on each other toes :-)

**Comment by mauritsvanrees** [comment]
Thanks for dancing with me. ;-)

**Pull request closed without merging**
