### PR TITLE
Update link

### PR DESCRIPTION
**Pull request by gforcada**
@svx @polyester is these docs planned to go/are they already in docs.plone.org?

Fixes https://github.com/plone/buildout.coredev/issues/141

### CODE REVIEW

**Comment by polyester** [comment]
yes, they are pulled in and show up at http://docs.plone.org/develop/coredev/docs/index.html so you might also want to point there.

**Comment by gforcada** [comment]
@polyester thanks, link updated!

**Comment by mauritsvanrees** [comment]
@gforcada Since you are fixing links, can you have a look at the Jenkins images that are linked to in this same readme? The Jenkins links are fine, but the images give a 404 and I don't know what url they should be.

**Comment by gforcada** [comment]
@mauritsvanrees that's from a [jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/Embeddable+Build+Status+Plugin) that was not installed. It should work now.

**Comment by gforcada** [comment]
I think it is ready to be merged, anyone willing to push the green button? :)

**Comment by mauritsvanrees** [comment]
Thanks Gil.

**Pull request merged**
