### PR TITLE
Fix windows

### PR DESCRIPTION
**Pull request by jensens**
Fix the buildout.coredev to run on windows. Adds Github Action to run buildout on windows.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
I have not tried it, but looks okay.
zope.sendmail 5.1 has been released meanwhile.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
