### PR TITLE
Try latest zope.testrunner

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by gforcada** [comment]
Trying it here: jenkins.plone.org/job/pull-request/60

**Comment by jensens** [comment]
looks fine, is there any reason against merge?

**Comment by gforcada** [comment]
I wanted to use this PR as a guinea pig for improving the pull request job on jenkins. As you can see it failed without running the tests. http://jenkins.plone.org/job/pull-request/60/console

And I remember there was some problems the last time it was tried (I think @tisto tried it).

So, no let's not merge it until we can ensure it will not break the build :)

**Comment by gforcada** [comment]
@jensens thanks for reminding me though!

**Comment by gforcada** [comment]
Running it once more: http://jenkins.plone.org/job/pull-request/106

**Comment by gforcada** [comment]
Trying once more: http://jenkins.plone.org/job/pull-request-5.0/28/

**Comment by gforcada** [comment]
There seems to be a newer version 4.4.9: http://jenkins.plone.org/job/pull-request-5.0/29

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/180/

**Comment by gforcada** [comment]
Another try will not hurt: http://jenkins.plone.org/job/pull-request-5.0/200/

**Comment by jensens** [comment]
another trial http://jenkins.plone.org/job/pull-request-5.0/313/

**Comment by mauritsvanrees** [comment]
My impression from last time that I tried this, for the Zope 2.13.23 update, was that the failures pointed to problems in the order of test layers. The new testrunner orders the layers in a better way, which should give a speed boost, but some tests fail because they rely on the old order. I might be wrong.

**Comment by gforcada** [comment]
I rebased the branch and triggered jenkins again: http://jenkins.plone.org/job/pull-request-5.0/403/

**Comment by gforcada** [comment]
Most of the errors seem to be about different date formatting...

**Comment by mauritsvanrees** [comment]
Plus this error from plone.supermodel in plone.autoform integration tests:

```
ConfigurationExecutionError: <type 'exceptions.AttributeError'>: 'VerifyingAdapterLookup' object has no attribute 'dependents'
  in:
  File "/home/jenkins/.buildout/eggs/plone.supermodel-1.2.6-py2.7.egg/plone/supermodel/configure.zcml", line 9.4-12.10
      <zcml:customAction
          handler=".model.finalizeSchemas"
          order="9999999"
          />
```

**Pull request merged**
