### PR TITLE
Use current ZODB (2nd trial)

### PR DESCRIPTION
**Pull request by jensens**
Tests were red after merge of #317 - we need to figure out what happened - they were green on PR before.

### CODE REVIEW

**Comment by gforcada** [comment]
Do you have the link to the jenkins job that failed?

**Comment by jensens** [comment]
Huh, after looking at it, it seems the merge before was the cause of the red Jenkins: http://jenkins.plone.org/job/plone-5.1-python-2.7/1753/
But there were no changes and the next one, finally green, was the ZODB merge:  http://jenkins.plone.org/job/plone-5.1-python-2.7/1754/
Overall, this is a bit confusing.

**Comment by jensens** [comment]
Now, the PR fails. I really have no idea what's going on here.

In parallel, I have the tests running local (w/o robot tests) and they seem to pass (still running, but some of the failed ones passed).

**Comment by jensens** [comment]
I start the tests again with more version pins (ZODB dependencies were not pinned). 

Unrelated, I also added ZRS and RelStorage to the ecosystem pins in order to help future users to not use outdated versions.

**Comment by jensens** [comment]
btw., local on my machine all tests are passing (w/o having robot tests run).

**Comment by jensens** [comment]
It fails again, this looks like a machine/setup/jenkins specific problem. I am a bit lost here.

**Comment by gforcada** [comment]
I have no idea, but someting looks really broken: http://jenkins.plone.org/job/pull-request-5.1/1456/consoleFull

**Comment by gforcada** [comment]
Given that the main jobs are green, it has to be due to the changes here...

**Comment by jensens** [comment]
@gforcada given that http://jenkins.plone.org/job/plone-5.1-python-2.7/1754/ was green: I am confused. May you explain this?

**Comment by jensens** [comment]
@gforcada some time (about a year IIRC) we had a similar situation where one node was broken and produced total failure while the others were working. No idea if this is related. 

Also, the broken build one commit before the ZODB5 merge in 5.1 branch and the subsequent green build of the merge signaling there is something wrong with Jenkins.

**Comment by gforcada** [comment]
Yes, that's true, node1 was the problematic one, but this last error happened on node5, which together with node6, are the latest nodes we have, and they should be fine...

**Comment by jensens** [comment]
@gforcada I am still curious why  http://jenkins.plone.org/job/plone-5.1-python-2.7/1754/ was green (it was this ZODB change). Any chance to figure out? There must be something unstable in the stack.

**Pull request closed without merging**
