### PR TITLE
Bump bootstrap

### LINKED ISSUE #169: Jenkins on 5.1 fails due to setuptools redirect problem
The last two 5.1 jobs failed.
http://jenkins.plone.org/job/plone-5.1-python-2.7/322/console says:

```
[plone-5.1-python-2.7] $ /bin/bash /tmp/hudson6037478439391730436.sh
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-19.4.zip
Extracting in /tmp/tmpn1Utau
Traceback (most recent call last):
  File "bootstrap.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 175, in use_setuptools
  File "<string>", line 126, in _do_download
  File "<string>", line 66, in _build_egg
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 105, in archive_context
  File "<string>", line 89, in __new__
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/tmp/tmpeYgEMn/setuptools-19.4.zip'
/tmp/hudson6037478439391730436.sh: line 5: bin/buildout: No such file or directory
/tmp/hudson6037478439391730436.sh: line 6: bin/alltests: No such file or directory
```

When I download the setuptools zip with curl, I get a '301 Moved permanently' with in html: "The resource has been moved to https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-19.4.zip; you should be redirected automatically."

The 5.0 pull request job I just started has the same: http://jenkins.plone.org/job/pull-request-5.0/1145/console
4.3 seems unaffected.

I don't immediately see where this is going wrong. Locally, I can run `python2.7 bootstrap.py --setuptools-version=19.4` just fine.

### PR DESCRIPTION
**Pull request by gforcada**
It should fix https://github.com/plone/jenkins.plone.org/issues/169

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Does not solve the Jenkins problem. But otherwise: +1.

**Comment by gforcada** [comment]
Oh now I see, the bootstraping is done before switching branches... I manually fixed the jenkins job to use setuptools 21.0.0 which seems to work

**Comment by mauritsvanrees** [comment]
Cool, thanks.
I'll merge this one. Jenkins is not finished yet, but the bootstrapping is, so this one seems good.

**Comment by gforcada** [comment]
@mauritsvanrees oops, you should have wait as jenkins.plone.org jobs need some fixing

**Comment by mauritsvanrees** [comment]
Oops, sorry, too fast. :(

**Comment by gforcada** [comment]
@mauritsvanrees no worries I _think_ I fixed everything, let's see what jenkins says

**Pull request merged**
