### PR TITLE
Update various dependencies with bug fix releases

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@plone/framework-team need review here.

@plone/testing-team tests seem to be staled.

**Comment by jensens** [comment]
+1 for merge, but I would really like to see green tests before, I just have no time to look at it myself.

**Comment by gforcada** [comment]
@hvelarde thanks for caring about 4.3 so much! I did some changes on the pull request jobs and I see that the 4.3 job fails due to the setup, would you mind waiting one or two days (hopefully this night European time) for me to fix it before merging?

All the version pins look fine, but the zope.testrunner I think is problematic: the 4.4.5 version did massively broke lots of tests in 5.x series, so I would expect even more breakage on 4.3.x

**Comment by gforcada** [comment]
@hvelarde it should be fixed, at least the setup, can not say about the pull request itself :wink:

**Comment by hvelarde** [comment]
seems this is not working; I'll try an incremental approach instead.

**Comment by hvelarde** [comment]
mmm, seems `Products.CMFCore = 2.2.12` is guilty of all broken tests.

**Comment by hvelarde** [comment]
@plone/framework-team the pull request is ready.

**Review by ale-rt — APPROVED** [review]

**Comment by ale-rt** [comment]
This looks fine to me! Thanks for the hard work!

**Pull request merged**
