### PR TITLE
Do not merge: test plone.i18n.git branch=cleanup-and-upgrade-unidecode-3

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by jensens** [comment]
@ale-rt What is missing here?

**Comment by ale-rt** [comment]
Coordination mainly.

This should not be merged because it uses a custom branch from this PR: https://github.com/plone/plone.i18n/pull/31

If https://github.com/plone/plone.i18n/pull/31 is merged then we need to make another PR with just the upgrade of the pin for unidecode.

**Comment by ale-rt** [comment]
Anyway I will rerun the tests after bumping again Unidecode

**Comment by ale-rt** [comment]
I have conflicts in rebasing https://github.com/plone/plone.i18n/pull/31 will postpone this for a bit

**Comment by jensens** [comment]
successor is https://github.com/plone/buildout.coredev/pull/736

**Pull request closed without merging**
