### PR TITLE
Update `robotframework-browser` version (and dependencies)

### PR DESCRIPTION
**Pull request by petschki**
Due to the progress here https://github.com/plone/Products.CMFPlone/pull/4019 we need up to date versions ...

### CODE REVIEW

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
The tests are flaky even after backporting the versions to rfbrowser <18 ... I'd suggest to bring the latest versions to coredev 6.1 and get the ported tests done here https://github.com/plone/Products.CMFPlone/pull/4019

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@gforcada the updated rfbrowser 18.8.1 doesn't work with the current node version ... on Node 4 it says:

```
2024-10-13 15:42:19,657 [INFO    ] npm WARN EBADENGINE   package: '@eslint/config-array@0.18.0',
2024-10-13 15:42:19,657 [INFO    ] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
2024-10-13 15:42:19,657 [INFO    ] npm WARN EBADENGINE   current: { node: 'v20.5.1', npm: '9.8.0' }
2024-10-13 15:42:19,657 [INFO    ] npm WARN EBADENGINE }
```

https://jenkins.plone.org/job/pull-request-6.1-3.12/740/console

**Pull request merged**
