### PR TITLE
Plip 2177

### PR DESCRIPTION
**Pull request by tisto**
see Plip plone/Products.CMFPlone#2177

### CODE REVIEW

**Comment by jensens** [comment]
It has to be added to ``sources.cfg`` too.

**Comment by tisto** [comment]
@jensens done. Added to sources.cfg.

**Comment by tisto** [comment]
https://jenkins.plone.org/job/pull-request-5.2/900/ passes.

**Comment by tisto** [comment]
https://jenkins.plone.org/job/pull-request-5.2/906/

**Comment by tisto** [comment]
This one should be green: https://jenkins.plone.org/job/pull-request-5.2/907/console

**Comment by tisto** [comment]
https://jenkins.plone.org/job/pull-request-5.2/909/ -> Green!

**Pull request merged**
