### PR TITLE
Update resources/theme/sunburst/rules.xml

### PR DESCRIPTION
**Pull request by Thomvl**
Fixed positioning with only portal-column-one active

### CODE REVIEW

**Comment by garbas** [comment]
@vangheem @TH-code i believe you're owners of plip 13355

**Comment by vangheem** [comment]
This shouldn't be in buildout and should now be removed. @TH-code can you do that? This work is being done in a different package right now. @garbas thanks for the heads up.

**Comment by TH-code** [comment]
@vangheem Yes I'll remove it (was already planning to but havent gotten round to it).

**Comment by TH-code** [comment]
@Thomvl This is an old plip branch, I'm removing it. In the meantime I've added the plip-13355 (note the '-') which has a set of startup diazothemes including boilerplate/initializr themes and sunburst and classic. The pull request should nog be necessary with those. But please try them out. The new plip-13355 basically adds diazotheme.startup which is on the collective.

**Pull request closed without merging**
