### PR TITLE
bump a couple of versions

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Review by mauritsvanrees — COMMENTED** [review]
LGTM, but there is an extra Jenkins failure for plone.app.widgets, for example:
https://jenkins.plone.org/job/pull-request-5.2/1744/testReport/junit/plone.app.widgets.tests.test_robot/RobotTestCase/As_a_contributor_I_can_enter_the_date_and_time/
I don't see an obvious candidate for a package version that may cause this.

**Comment by pbauer** [comment]
Maybe it is due to upgrading robotframework  from 3.0.4 to 3.1. I'll check that locally.

**Comment by pbauer** [comment]
That was it. I'll start a new job and we'll deal with the robotframework upgrade later.

**Comment by gforcada** [comment]
@pbauer thanks for spotting the error!!

**Comment by mauritsvanrees** [comment]
Jenkins is mostly happy, but the remaining failures are known issues with the robot tests (fixed in CMFPlone today, phew) or random failures. I will merge. Thanks!

**Comment by gforcada** [comment]
Well, actually on Chrome it used to pass all tests if I remember correctly.

**Pull request merged**
