### PR TITLE
Upgrade robotframework related pins (5.1)

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
Tested with
```
https://github.com/plone/buildout.coredev/pull/544
https://github.com/plone/plone.app.widgets/pull/189
https://github.com/plone/Products.CMFPlone/pull/2615
```

**Comment by ale-rt** [comment]
@plone/testing-team I am quitre puzzled :)
If I start a 5.1 PR job with:
```
https://github.com/plone/buildout.coredev/pull/544
```
it works, but when I start it with:
```
https://github.com/plone/buildout.coredev/pull/544
https://github.com/plone/plone.app.widgets/pull/189
https://github.com/plone/Products.CMFPlone/pull/2615
```
It fails complaining that this PR branch does not exist, see https://jenkins.plone.org/job/pull-request-5.1/1629/console:
```
...
[pull-request-5.1] $ /bin/sh -xe /tmp/shiningpanda2609090602619016525.sh
+ [ 1 = 1 ]
+ git checkout update-robot-keywords-51
error: pathspec 'update-robot-keywords-51' did not match any file(s) known to git.
Build step 'Virtualenv Builder' marked build as failure
...
```

**Comment by ale-rt** [comment]
I merged https://github.com/plone/plone.app.widgets/pull/189 to fix the Plone 5.2 build but I think that is going to break the 5.1, I apologize for that.
Anyway all should be fixed by merging this one and https://github.com/plone/Products.CMFPlone/pull/2615

**Comment by gforcada** [comment]
Merge all them then.

I think that a buildout.coredev branch and other branches do not work together

**Pull request merged**
