### PR TITLE
Update Products.MailHost to 4.10.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
I saw test failures earlier when I tried it in combination with other new packages.
Now let's try it on its own.
I expect failures due to the changes here: https://github.com/zopefoundation/Products.MailHost/issues/30

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
`initial_value must be str or None, not bytes` when doing:
```
    msg = message_from_string(mails.messages[0])
```
means that this should be fixed by changing the line to:
```
    msg = message_from_string(safe_nativestring(mails.messages[0]))
```
right?
But probably there are some other places where we should apply this `safe_nativestring`.

**Comment by mauritsvanrees** [comment]
On Python 3 we can call `email.message_from_bytes`. I have a branch for CMFPlone ready just now that does this. But other types of fixes are needed too.

**Comment by mauritsvanrees** [comment]
CMFPlone should be fixed now. Let's check the progress:

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
All green! :-)

**Review by ale-rt — APPROVED** [review]
Great work!

**Comment by mauritsvanrees** [comment]
Note that the `plone.api` PR is currently being [tested on Plone 5.1](https://github.com/plone/plone.api/pull/443#issuecomment-698855195).

And https://github.com/plone/plone.app.testing/pull/70 is failing on Travis because it is being tested there with the current coredev versions, so still the older Products.MailHost; that should be fixed automatically when we merge this. And Travis also fails because the `lint` jobs fail, but this has nothing to do with the PR itself. That could be fixed in a separate PR.

**Comment by mauritsvanrees** [comment]
The points from my last comment have been addressed: `plone.api` passes on 5.1, and `plone.app.testing` Travis lint tests pass.
For me, this is ready to merge.
Steps to take:

- [x] close this coredev PR, because we do not want to change the branch names
- [x] instead, update the `Products.MailHost` pin to 4.10.
- [x] Merge all PRs mentioned in https://github.com/plone/Products.CMFPlone/issues/3178.

Do we agree that this is ready to merge?

If so, either I or someone else could do these steps.

**Comment by ale-rt** [comment]
> Do we agree that this is ready to merge?

It seems the way to go for me. I would leave this to you because you have pretty clear in mind the steps to do.
Thanks for the huge effort!

**Comment by jensens** [comment]
I would leave this to you @mauritsvanrees too.

**Comment by mauritsvanrees** [comment]
All done and merged. Thanks for the reviews!

**Pull request closed without merging**
