### PR TITLE
update versions according to hotfix

### PR DESCRIPTION
**Pull request by jensens**
https://plone.org/products/plone-hotfix/releases/20151006
also adds plone4.csrffixes to sources

### CODE REVIEW

**Comment by jensens** [comment]
w/o PlonePAS http://jenkins.plone.org/job/pull-request-4.3/142/console 
with new PlonePAS http://jenkins.plone.org/job/pull-request-4.3/143/

**Comment by gforcada** [comment]
plone.namedfile needs to  be updated as well

**Comment by gforcada** [comment]
@jensens I added some more packages and fixes (and force rebased on top of 4.3.x branch to get the recent merge of plone.contentrules)

Let's see how much is still needed: http://jenkins.plone.org/job/pull-request-4.3/144/

**Comment by gforcada** [comment]
ATContenttypes tests should be fixed now: http://jenkins.plone.org/job/pull-request-4.3/145/

**Comment by jensens** [comment]
may we test this plip like? would be great to test mre than one PR at once...

**Comment by gforcada** [comment]
@jensens actually everything should be already in place for testing this, as long as you keep updating checkouts.cfg and sources.cfg :-)

As for testing more than one PR, I will try to get some time to look at it, no promises though

**Comment by jensens** [comment]
rebased, new test here http://jenkins.plone.org/job/pull-request-4.3/150/

**Comment by gforcada** [comment]
rebased again, tests will still fail, but anyhow: http://jenkins.plone.org/job/pull-request-4.3/151

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-4.3/166/ rebased again, tests will still fail

**Comment by jensens** [comment]
@gforcada how do we proceed with this one?

**Comment by gforcada** [comment]
@jensens we either fix all the broken tests by cherry-picking upstream commits or fixing it on our own, or we disable CRSF on tests...

The first takes a lot more time but it's the "good way to go" while the other basically cheats so we can get a release out...

I would prefer to do the first one, but I have not so much knowledge about all the broken tests, so it's really time consuming for someone like me.

**Comment by gforcada** [comment]
@jensens that's interesting, tests did pass now...

**Comment by jensens** [comment]
@gforcada self-healing code? fun :D We should check carefully why this pass and if theres no problem left I'd say a merge would be ok. Since this is a large improvement, @esteele so you think its ok to get a release out? Maybe with tomorrow hotfix applied as well?

**Comment by mauritsvanrees** [comment]
I was wondering where the latests apparently passing Jenkins test was, but I see it here, indeed passing: http://jenkins.plone.org/job/pull-request-4.3/178/

It needs a rebase according to github, but I see the conflict is only in checkouts.cfg which can be easily solved manually when merging.

**Comment by jensens** [comment]
rebased and green. i dont have time for a bigger merge session. if anybody wants to please do. i can come back to it later this week/

**Comment by gforcada** [comment]
I rebased again and tests are running here: http://jenkins.plone.org/job/pull-request-4.3/184 it it keeps green I will try to merge everything.

**Comment by gforcada** [comment]
Sorry fall asleep, maybe tonight :-)

**Comment by gforcada** [comment]
Rebased once more and tests are running again.

**Comment by gforcada** [comment]
I bumped Products.PlonePAS to also include Hotfix 2015-12-08 (@mauritsvanrees already integrated and released the hotfix on Products.PlonePAS).

**Comment by gforcada** [comment]
I did some more changes here and there, hopefully if everything runs fine, then we can finally merge :-)

**Comment by gforcada** [comment]
Merged!

**Comment by gforcada** [comment]
Seems that something is broken on the pull request jobs... tests now are failing... :-/

**Comment by gforcada** [comment]
pull requests jobs fixed with https://github.com/plone/jenkins.plone.org/commit/44bf22da668058a6ef1ec7f0740eaf1202d5b87e

**Pull request closed without merging**
