### PR TITLE
Update 4.3 to Zope 2.13.23

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Pull request number 100. :-)

http://jenkins.plone.org/job/pull-request-4.3/66/

**Comment by mauritsvanrees** [comment]
Several errors are emerging, just like for #99 (plone 5 branch).

**Comment by mauritsvanrees** [comment]
http://jenkins.plone.org/job/pull-request-4.3/67/console

**Comment by mauritsvanrees** [comment]
Let's give this another go too, Jenkins:
http://jenkins.plone.org/job/pull-request-4.3/89/

**Comment by mauritsvanrees** [comment]
Okay, that one will fail. Time for a rebase and a forced push. Trying again:
http://jenkins.plone.org/job/pull-request-4.3/90/

**Comment by mauritsvanrees** [comment]
Failing tests in Jenkins:

```
Products.CMFPlone.tests.test_robot.RobotTestCase.Scenario New user overlay closes on valid data
Products.CMFPlone.tests.test_robot.RobotTestCase.Scenario Select All items
plone.app.jquerytools.tests.ploneIntegration.txt
```

It seems the newer zope.testrunner may have something to do with it, due to changes in the order of test layers. With 4.4.9 I get this error locally:

```
$ bin/test -s Products.CMFDiffTool
...
Running Products.CMFDiffTool.testing.PackageLayer tests:
  Tear down Products.CMFDiffTool.tests.BaseTestCase.CMFDiffToolLayer in 0.195 seconds.
  Set up collective.testcaselayer.ptc.PTCLayer Traceback (most recent call last):
  File "/Users/mauritsvanrees/shared-eggs/zope.testrunner-4.4.9-py2.6.egg/zope/testrunner/runner.py", line 411, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/Users/mauritsvanrees/shared-eggs/zope.testrunner-4.4.9-py2.6.egg/zope/testrunner/runner.py", line 719, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/Users/mauritsvanrees/shared-eggs/zope.testrunner-4.4.9-py2.6.egg/zope/testrunner/runner.py", line 719, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/Users/mauritsvanrees/shared-eggs/zope.testrunner-4.4.9-py2.6.egg/zope/testrunner/runner.py", line 719, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/Users/mauritsvanrees/shared-eggs/zope.testrunner-4.4.9-py2.6.egg/zope/testrunner/runner.py", line 724, in setup_layer
    layer.setUp()
  File "/Users/mauritsvanrees/shared-eggs/collective.testcaselayer-1.6.1-py2.6.egg/collective/testcaselayer/sandbox.py", line 41, in setUp
    result = super(Sandboxed, self).setUp()
  File "/Users/mauritsvanrees/shared-eggs/collective.testcaselayer-1.6.1-py2.6.egg/collective/testcaselayer/ztc.py", line 51, in setUp
    self.portal = self._portal()
  File "/Users/mauritsvanrees/shared-eggs/Products.PloneTestCase-0.9.18-py2.6.egg/Products/PloneTestCase/PloneTestCase.py", line 70, in _portal
    portal = self.getPortal()
  File "/Users/mauritsvanrees/shared-eggs/Products.PloneTestCase-0.9.18-py2.6.egg/Products/PloneTestCase/PloneTestCase.py", line 107, in getPortal
    return getattr(self.app, portal_name)
AttributeError: plone

Tearing down left over layers:
  Tear down Products.PloneTestCase.layer.PloneSite in 0.001 seconds.
  Tear down Products.PloneTestCase.layer.ZCML in 0.006 seconds.
  Tear down Testing.ZopeTestCase.layer.ZopeLite in 0.000 seconds.
Total: 60 tests, 0 failures, 1 errors, 0 skipped in 18.399 seconds.
```

Reverting to 4.4.4 fixes that error. See also pull request #72 that only updates the zope.testrunner version.

So go ahead again, Jenkins: http://jenkins.plone.org/job/pull-request-4.3/91/

**Comment by mauritsvanrees** [comment]
Hah, now Jenkins passes. Woohoo!
Review please.

**Comment by pbauer** [comment]
@mauritsvanrees why do you update robotframework-stuff as well (to newer versions than P5 uses)? That should be a different PR.

**Comment by mauritsvanrees** [comment]
I had super good reasons for this. Probably. I don't know them anymore. ;-)
Let's try again with minimum changes. I rebased, edited, and did a forced push on this branch.
Jenkins, go ahead: http://jenkins.plone.org/job/pull-request-4.3/96/

**Comment by mauritsvanrees** [comment]
Jenkins is happy as a puppy.

**Pull request merged**
