### PR TITLE
Include plone.app.stagingbehavior

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by jensens** [comment]
What is the plan here?

**Comment by pbauer** [comment]
rebased. test: http://jenkins.plone.org/job/pull-request-5.0/303/

**Comment by pbauer** [comment]
There are test-failures: http://jenkins.plone.org/job/pull-request-5.0/303/

**Comment by vangheem** [comment]
latest plone.app.iterate implements dexterity checkin/checkout support. plone.app.staging is deprecated at this point for plone 5.

**Comment by pbauer** [comment]
Oh, I forgot that! Thanks for clarifying.

**Pull request closed without merging**
