### PR TITLE
Update chameleon version

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tisto** [comment]
Testing the pr: http://jenkins.plone.org/job/pull-request/141/

@gforcada testing buildout.coredev pull requests works, right?

**Comment by gforcada** [comment]
@tisto yes, that was a later addition, but now it works :)

**Comment by tomgross** [comment]
Unfortunately there are 2 test failures: https://github.com/zopefoundation/five.pt/issues/4

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/30/

**Comment by tomgross** [comment]
This is superseded by #91

**Pull request closed without merging**
