### PR TITLE
Update zc.buildout

### PR DESCRIPTION
**Pull request by gforcada**
Use the latest one available: 2.3.1

### CODE REVIEW

**Comment by gforcada** [comment]
Tests running at: http://jenkins.plone.org/job/pull-request/212

**Comment by jensens** [comment]
:+1:

**Comment by jensens** [comment]
At the same time we could update setuptools as well.
We're at setuptools==5.8 at the moment.

At pypi it is at 17.0 https://pypi.python.org/pypi/setuptools/17.0

In my projects (Plone 4.3 and 5)  I use always latest setuptools at the moment (I do reset the version setting with "setuptools =", anyway I do not recommend this for coredev).

**Comment by gforcada** [comment]
@jensens as usual there are some test problems (although solved just pending a release to be made) https://github.com/plone/buildout.coredev/pull/82

**Comment by tomgross** [comment]
Latest buildout version is now 2.4.0: https://pypi.python.org/pypi/zc.buildout/2.4.0

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/139/

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/140/

**Comment by pbauer** [comment]
There is a new release of GenericSetup with the fixes needed to run the newest setuptools (https://github.com/zopefoundation/Products.GenericSetup/issues/10). Are there any objections against adding `setuptools = 18.0.1` to this pr?

**Comment by jensens** [comment]
Btw,. a curiosity: Jenkins does a `/usr/bin/python2.7 bootstrap.py --setuptools-version=8.3 -c jenkins.cfg` but before in versions.cfg we fixed to `setuptools = 5.8`.

**Comment by jensens** [comment]
@pbauer thx, next trial: http://jenkins.plone.org/job/pull-request-5.0/141/

**Comment by jensens** [comment]
TEST PASSED :+1: 
Any reason against a merge?

**Comment by jaroel** [comment]
I'm game!
Maybe @tisto?

**Comment by tisto** [comment]
setuptools 8.3 is the earliest version that works with "--setuptools-version". Therefore this is the earliest version that we can pin. This was done when setuptools/buildout was very fragile. I'm ok with upgrading if the build is green.

**Pull request merged**
