### PR TITLE
Update package versions for 6.0, 2023-07-13.

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
@mauritsvanrees we need this for 6.1 too, right?

**Comment by mauritsvanrees** [comment]
Yes, see PR #877 :-)

**Pull request merged**
