### PR TITLE
Remove cruft

### PR DESCRIPTION
**Pull request by gforcada**
@plone/release-team @plone/framework-team @plone/testing-team to the best of my knowledge these files are not being used by jenkins nor referenced by any other cfg that is being used.

Is anyone against removing them? :thinking:  speak up if you do! :smile:

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM

**Comment by mauritsvanrees** [comment]
The Jenkins PR job [gives an error](https://jenkins.plone.org/job/pull-request-5.2/873/console
):

```
IOError: [Errno 2] No such file or directory:
 '/home/jenkins/workspace/pull-request-5.2/themepreview.cfg'
```

So `themepreview.cfg` is still used. Maybe it shouldn't be.

**Comment by mauritsvanrees** [comment]
`core.cfg` extends `themepreview.cfg` since 2014, see commit 4ca19a52c8 by Asko.

@datakurre: Is `themepreview.cfg` still needed? If so, should it be merged into `core.cfg`?
It makes two scripts `themepreview-build` and `themepreview-pybot`. Are those still useful, and perhaps used in Jenkins?

**Comment by datakurre** [comment]
I believe that themepreview files can be removed

themepreview jobs got broken at jenkins long time ago, and I have not been able to fix them

**Comment by gforcada** [comment]
:sweat_smile: sorry I did not check for that one seems, but if @datakurre agrees, I will remove the traces.

**Pull request merged**
