### PR TITLE
[6.0] Update PyJWT to 2.3.0

### PR DESCRIPTION
**Pull request by jensens**
Needs merge with https://github.com/plone/plone.restapi/pull/1194 to not fail in tests.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

(expected to fail in plone.restapi)

**Comment by fredvd** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Replaced by PR #794 which was merged today.

**Pull request closed without merging**
