### PR TITLE
Go back from Zope 4.4.4 to 4.3.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Do keep a few updated packages.

There are various changes in how templates are rendered,
and especially which variables are available.
In path expressions, you can no longer use True or False, and 'attrs' is not defined.

See among others:
https://github.com/plone/Products.CMFPlone/issues/3135
https://community.plone.org/t/plone-5-2-2-soft-released/12487/43

We will have to see if we want this PR, or wait till problems are resolved in chameleon/tales.
But let's first run the tests.

cc @plone/release-team @plone/framework-team

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
One [failure on `plone.app.imaging`](https://jenkins.plone.org/job/pull-request-5.2/1392/testReport/plone.app.imaging.tests.test_new_scaling/ImagePublisherTests/testPublishWebDavScaleViaUID/
) in the 2.7 job, possibly caused by the namedfile/scale changes. But a bit strange that this same test goes fine on Zope 4.4.4 and not on 4.3. Well, 4.4 has slightly better webdav I think.

```
204 != 200

  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.imaging-2.1.1-py2.7.egg/plone/app/imaging/tests/test_new_scaling.py", line 162, in testPublishWebDavScaleViaUID
    self.assertEqual(response.getStatus(), 200)
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
```

**Comment by pbauer** [comment]
Made obsolete by https://github.com/plone/buildout.coredev/pull/664

**Comment by ale-rt** [comment]
To be clear @mauritsvanrees feel free to reopen this PR if you still feel that Plone 5.2.2 should have Zope 4.3.
I think there is no need to say that I totally trust your judgement and that this is a widely shared opinion :)

**Pull request closed without merging**
