### PR TITLE
[5.2] Update build tools

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@ale-rt this is already part of https://github.com/plone/buildout.coredev/pull/565

**Comment by ale-rt** [comment]
Oh did not notice that PR @pbauer.
Note that the pull-request-5.2 on py27 build is broken (and of course also https://jenkins.plone.org/job/plone-5.2-python-2.7/)

**Comment by ale-rt** [comment]
I am closing this because #565 is more complete

**Pull request closed without merging**
