### PR TITLE
Checkout Products.MailHost branch for line separator fixes.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Add Products.MailHost to the test-eggs too, for now.
This is for testing https://github.com/zopefoundation/Products.MailHost/pull/36
This might mean tests need updating, or maybe production code.
Let's see.
This is not for merging, only for testing.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by 1letter** [comment]
@mauritsvanrees The errors in the Jenkins Console are not from my patch?

**Comment by mauritsvanrees** [comment]
All have this: "Build timed out (after 180 minutes). Marking the build as aborted."
Maybe there were many concurrent jobs.
Let's try again before we dive deeper:

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
The new jobs are also stalled, already taking two hours. I guess this is because I added `Products.MailHost` to the `test-eggs`, which apparently has some unwanted side effect, and is not really necessary.
I undid that part, rebased, and force pushed.
Try again:

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
The Products.MailHost PR has been merged. This PR is no longer necessary.

**Pull request closed without merging**
