### PR TITLE
Update robotframework-selenium2library

### PR DESCRIPTION
**Pull request by ale-rt**
robotframework-selenium2library = 3.0.0 is compatible with Python 3

### CODE REVIEW

**Comment by ale-rt** [comment]
Ouch! Prefer #407 to this one

**Comment by jensens** [comment]
@ale-rt so close this one?

**Comment by ale-rt** [comment]
It does not harm to merge, given that #407 is failing now

**Comment by gforcada** [comment]
Let's merge this one (I already did :smile: ) as the other one will take some more time before we can merge it. If anyone feels like running the robot tests locally and fix the issues on FF +58 it would be great :-)

**Pull request merged**
