### PR TITLE
Replace version pin on slimit with calmjs.parse

### PR DESCRIPTION
**Pull request by metatoaster**
As required by plone/Products.CMFPlone#2616.

### CODE REVIEW

**Comment by gforcada** [comment]
@metatoaster this needs to be merged on branch **5.2**, it *might* be backported to 5.1, but so far it should be only for 5.2 branch

many thanks for unlocking this blocker!! :bowing_man:

**Comment by metatoaster** [comment]
Whoops, I was wondering why 5.1 was showing up for the CI. Thanks for pointing out this obvious mistake, and this looks more like it now.

**Comment by metatoaster** [comment]
Ah, I only just noticed the notes on the special pinning on the `ply` package.  For the `calmjs.parse` wheel releases I can only pre-generate the *tab module files with only the supported released versions of `ply` thus far, so pinning to 3.11 (the current/latest released version as of now) is safe.  Should I also update the rest of the `versions.cfg` with this information?

**Comment by gforcada** [comment]
@metatoaster yes, if that makes jenkins go green, sure.

There should be a pull request on cmfplone as well, or is that one already merged? :thinking:

**Comment by metatoaster** [comment]
@gforcada I updated the note and removed that extra "temporary" redefinition as that is now the definitive one (but kept `ply` at the "Special pin" section).  Neither this nor my change on CMFPlone has been merged yet.  I also took the opportunity to update the version pin as sadly I failed to account for an irregular syntax case with the JavaScript language grammar which I just released a fixed (via calmjs.parse-1.1.3). Should hopefully be the last one I missed (which should have been eradicated the first time I encountered that for the `function` keyword, but hindsight, etc...)

**Comment by pbauer** [comment]
Since https://github.com/plone/Products.CMFPlone/pull/2616 works now I'll merge this.

**Pull request merged**
