### PR TITLE
towards zope 4.2.1

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
Needs merge of all following:
- [x] plone.app.discussion https://github.com/plone/plone.app.discussion/pull/168
- [x] collective.xmltestreport https://github.com/collective/collective.xmltestreport/pull/25

The next all at once
- [x] plone.supermodel https://github.com/plone/plone.supermodel/pull/36
- [x] plone.testing https://github.com/plone/plone.testing/pull/72
- [x] plone.app.testing https://github.com/plone/plone.app.testing/pull/68

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM, but some related PRs have already been merged, and branches deleted. I will leave merging to you.

**Comment by jensens** [comment]
will continue on fresh branch

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request closed without merging**
