### PR TITLE
upgrade unidecode to latest

### PR DESCRIPTION
**Pull request by jensens**
~~goes with https://github.com/plone/plone.i18n/pull/21~~

The tests passed, see: https://github.com/plone/buildout.coredev/pull/573

After merging this please merge: https://github.com/plone/plone.i18n/pull/31

### CODE REVIEW

**Comment by ale-rt** [comment]
I merged master into the plone.i18n branch and made a new PR:
- https://github.com/plone/buildout.coredev/pull/401
- https://github.com/plone/plone.i18n/pull/31
```
https://github.com/plone/buildout.coredev/pull/401
https://github.com/plone/plone.i18n/pull/31
````

**Comment by ale-rt** [comment]
This is failing in a strange way:
```
+ git checkout cleanup-and-upgrade-unidecode-3
error: pathspec 'cleanup-and-upgrade-unidecode-3' did not match any file(s) known to git.
```
but the branch is there: https://github.com/plone/plone.i18n/tree/cleanup-and-upgrade-unidecode-3
:thinking: 

CC @plone/testing-team

**Comment by gforcada** [comment]
@ale-rt the *problem* is that handling buildout.coredev **and** other packages branches is not supported right now on jenkins.plone.org :sweat_smile:

**Comment by ale-rt** [comment]
Thank you very much @gforcada.
I am trying to run the tests with https://github.com/plone/buildout.coredev/pull/573
I hope it makes sense

**Comment by jensens** [comment]
Lets close this as if it not work anyway.

**Pull request closed without merging**
