### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fix link to the
contributor's pdf

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
Is this good? Or do I need to make any more changes?

**Comment by mrsaicharan1** [comment]
This is in reference to #411 .

**Comment by gforcada** [comment]
Yes, it is. Would you mind doing the same for the 5.2 branch? TIA

**Comment by mrsaicharan1** [comment]
Yes,I will surely do it!

**Pull request merged**
