### PR TITLE
 Update robot test framework versions

### PR DESCRIPTION
**Pull request by thet**
Update robot test framework versions including Selenium to work with recent firefox releases.

Otherwise it fails with:

```
Failure in test Scenario As a member I want to be able to log into the website (test_example.robot)
Traceback (most recent call last):
  File "/home/thet-data/dotfiles-thet/home/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/thet-data/dotfiles-thet/home/.buildout/eggs/robotsuite-1.6.1-py2.7.egg/robotsuite/__init__.py", line 455, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Setup failed:
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

### CODE REVIEW

**Comment by thet** [comment]
By the way, I upgraded all versions in the `# Robot Testing`. Let's see, if it goes green with these changes.

**Comment by thet** [comment]
@gforcada you referenced this pull request. by accident?
i was about to close it, delete the branch and start all over, since the tests failed.

**Comment by jensens** [comment]
wait, I'am just figuring out whats up, its the tests partly at least

**Comment by jensens** [comment]
see plone/Products.CMFPlone#1321

**Comment by thet** [comment]
http://jenkins.plone.org/job/pull-request-5.0/718/

**Comment by thet** [comment]
New attempt with less updates: https://github.com/plone/buildout.coredev/pull/195

**Pull request closed without merging**
