### PR TITLE
Update Pillow from 6 to 8.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
I briefly tried Python 3.9 locally and could not install Pillow 6.2.2 due to a zlib problem.
Latest version 8.0.1 installed without problem.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
This gives a few test failures that indicate some changes in code are needed. Only `PlonePAS` and `plone.formwidget.namedfile` are affected.

```
Failed doctest test for Products.PlonePAS.utils.scale_image
  File "/home/jenkins/.buildout/eggs/cp38/Products.PlonePAS-6.0.6-py3.8.egg/Products/PlonePAS/utils.py", line 41, in scale_image

----------------------------------------------------------------------
File "/home/jenkins/.buildout/eggs/cp38/Products.PlonePAS-6.0.6-py3.8.egg/Products/PlonePAS/utils.py", line 69, in Products.PlonePAS.utils.scale_image
Failed example:
    scale_image(invalid, (50, 50))
Expected:
    Traceback (most recent call last):
    ...
    OSError: cannot identify image file...
Got:
    Traceback (most recent call last):
      File "/srv/python3.8/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Products.PlonePAS.utils.scale_image[13]>", line 1, in <module>
        scale_image(invalid, (50, 50))
      File "/home/jenkins/.buildout/eggs/cp38/Products.PlonePAS-6.0.6-py3.8.egg/Products/PlonePAS/utils.py", line 142, in scale_image
        image = Image.open(image_file)
      File "/home/jenkins/.buildout/eggs/cp38/Pillow-8.0.1-py3.8-linux-x86_64.egg/PIL/Image.py", line 2873, in open
        raise ValueError(
    ValueError: StringIO cannot be used to open an image. Binary data must be used instead.
----------------------------------------------------------------------
File "/home/jenkins/.buildout/eggs/cp38/Products.PlonePAS-6.0.6-py3.8.egg/Products/PlonePAS/utils.py", line 73, in Products.PlonePAS.utils.scale_image
Failed example:
    scale_image(sneaky, (50, 50))
Expected:
    Traceback (most recent call last):
    ...
    OSError: cannot identify image file...
Got:
    Traceback (most recent call last):
      File "/srv/python3.8/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest Products.PlonePAS.utils.scale_image[14]>", line 1, in <module>
        scale_image(sneaky, (50, 50))
      File "/home/jenkins/.buildout/eggs/cp38/Products.PlonePAS-6.0.6-py3.8.egg/Products/PlonePAS/utils.py", line 142, in scale_image
        image = Image.open(image_file)
      File "/home/jenkins/.buildout/eggs/cp38/Pillow-8.0.1-py3.8-linux-x86_64.egg/PIL/Image.py", line 2873, in open
        raise ValueError(
    ValueError: StringIO cannot be used to open an image. Binary data must be used instead.


  File "/srv/python3.8/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/srv/python3.8/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/srv/python3.8/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/srv/python3.8/lib/python3.8/doctest.py", line 2197, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
```

```
File "/home/jenkins/.buildout/eggs/cp38/plone.formwidget.namedfile-2.1.0-py3.8.egg/plone/formwidget/namedfile/widget.rst", line 755, in widget.rst
Failed example:
    PIL.Image.open(six.BytesIO(content.image_field))
Expected:
    Traceback (most recent call last):
    ...
    OSError: cannot identify image file...
Got:
    Traceback (most recent call last):
      File "/srv/python3.8/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest widget.rst[264]>", line 1, in <module>
        PIL.Image.open(six.BytesIO(content.image_field))
      File "/home/jenkins/.buildout/eggs/cp38/Pillow-8.0.1-py3.8-linux-x86_64.egg/PIL/Image.py", line 2943, in open
        raise UnidentifiedImageError(
    PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f086a8ded60>


  File "/srv/python3.8/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/srv/python3.8/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/srv/python3.8/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/srv/python3.8/lib/python3.8/doctest.py", line 2197, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
```

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
This is a blocker for Plone 6, because officially Pillow 6.2.2 does not support Python 3.9

Screenshot from 2021-06-23 16-02-15
https://pillow.readthedocs.io/en/latest/installation.html

**Comment by jensens** [comment]
PRs pending
- https://github.com/plone/Products.PlonePAS/pull/61
-  https://github.com/plone/plone.formwidget.namedfile/pull/50

**Comment by mauritsvanrees** [comment]
I have merged your PRs. Thanks!

I have rebased this branch on 6.0 and force pushed, to be sure we have the related packages added to the checkouts.

Jenkins should be busy now, with two PRs merged, but let's try:

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Green, I merge. Thanks for the assistance.

**Pull request merged**
