### PR TITLE
update robot versions

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Comment by thet** [comment]
http://jenkins.plone.org/job/pull-request-5.1/26/

**Comment by gforcada** [comment]
@thet I fixed a wrong version pin and at the same time you made me notice about a bug in the pull request github report script. Thanks :-)

**Comment by gforcada** [comment]
Running bin/buildout shows me that there is a version not pinned:

```
robotframework-selenium2screenshots = 0.6.0
```

@plone/release-team should we pin that one in versions.cfg ?

**Comment by jensens** [comment]
#202 supersedes this one, right?

**Comment by jensens** [comment]
otherwise reopen

**Comment by thet** [comment]
#202 is for 5.0. I reopen.

**Pull request closed without merging**
