### PR TITLE
NOT FOR MERGE: Test restapi change with coredev update.

### PR DESCRIPTION
**Pull request by jensens**
see https://github.com/plone/plone.restapi/pull/1194

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
The branch testing seems not to work with Jenkins? I think I saw it working on some of @mauritsvanrees branches.

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@jensens It seems that only PRs that point to the 6.0 and 5.2 branches run Jenkins. This PR was pointing to the update-pyjwt branch. I pointed it to branch 6.0 and now Jenkins runs.

@mauritsvanrees  It would be nice if all PRs run Jenkins.

**Comment by mauritsvanrees** [comment]
Problem is that when you create a PR to merge branch A into branch B, and branch B is not one of the standard branches, then Jenkins has no idea what to do with it. For starters, it has no idea which Python versions to test this with.

**Pull request closed without merging**
