### PR TITLE
Remove CMFDefault from buildout config

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/24/

**Comment by gforcada** [comment]
@tomgross there has to be some traces of CMFDefault somewhere as there is an error when tearing down some tests, see http://jenkins.plone.org/job/pull-request-5.0/24/consoleFull

I started it once more just to check it: http://jenkins.plone.org/job/pull-request-5.0/26

**Comment by gforcada** [comment]
I guess the error on jenkins is about the ZEXP used by plone.app.upgrade to do the upgrades, on that ZEXP there has to be a reference to CMFDefault.

The traceback:

```
Running plone.app.upgrade.v50.testing.plone.app.upgrade:4.0 -> 5.0 tests:
  Tear down plone.app.theming.testing.Theming:Integration in 0.000 seconds.
  Tear down plone.app.theming.testing.Theming in 0.003 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes in 0.259 seconds.
  Tear down plone.app.event.testing.PAEventLayer in 0.006 seconds.
  Set up plone.app.upgrade.v50.testing.RealUpgradeLayer Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 400, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 713, in setup_layer
    layer.setUp()
  File "/home/jenkins/workspace/pull-request-5.0/src/plone.app.testing/plone/app/testing/helpers.py", line 350, in setUp
    self.setUpPloneSite(portal)
  File "/home/jenkins/workspace/pull-request-5.0/src/plone.app.upgrade/plone/app/upgrade/v50/testing.py", line 18, in setUpPloneSite
    app._importObjectFromFile(path, verify=0)
  File "/home/jenkins/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 645, in _importObjectFromFile
    filepath, customImporters=customImporters)
  File "/home/jenkins/.buildout/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/ExportImport.py", line 92, in importFile
    t.savepoint(optimistic=True)
  File "/home/jenkins/.buildout/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 260, in savepoint
    self._saveAndRaiseCommitishError() # reraises!
  File "/home/jenkins/.buildout/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 257, in savepoint
    savepoint = Savepoint(self, optimistic, *self._resources)
  File "/home/jenkins/.buildout/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 690, in __init__
    savepoint = savepoint()
  File "/home/jenkins/.buildout/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 1123, in savepoint
    self._commit(None)
  File "/home/jenkins/.buildout/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 587, in _commit
    self._importDuringCommit(transaction, *self._import)
  File "/home/jenkins/.buildout/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/ExportImport.py", line 176, in _importDuringCommit
    pickler.dump(unpickler.load())
ImportError: No module named CMFDefault.MetadataTool
```

So, most probably we need an upgrade step to remove CMFDefault metadata tool :)

**Comment by tomgross** [comment]
Try again, after https://github.com/plone/plone.app.upgrade/pull/35 is merged

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.0/40/

**Pull request merged**
