### PR TITLE
remove most formlib packages

### PR DESCRIPTION
**Pull request by tomgross**
Merge https://github.com/plone/Products.CMFPlone/pull/593 first

### CODE REVIEW

**Comment by gforcada** [comment]
@vangheem @tomgross could next time make a rebase? we just merged +100 useless commits for no good reason and actually just cluttering, the already cluttered git history of buildout.coredev...

Actually I was trying that by myself and was unable to see what was actually changed within this forest of commits.

I wrote some helpful tips here: http://buildoutcoredev.readthedocs.org/en/latest/git.html

**Comment by vangheem** [comment]
yah, my bad. I noticed it too late. I apologize for that. Should I amend history?

**Comment by gforcada** [comment]
@vangheem no, that would be even worse, as rewriting an already published tree can cause lots of troubles to people...

**Comment by vangheem** [comment]
@tomgross fyi, you can setup git to automatically rebase for you on pull: https://github.com/plone/plone.dotfiles/blob/master/.gitconfig#L67

**Pull request merged**
