### PR TITLE
Refactor 5.2 python 2 and 3

### PR DESCRIPTION
**Pull request by pbauer**
This fixes https://github.com/plone/Products.CMFPlone/issues/2593

### CODE REVIEW

**Comment by gforcada** [comment]
@pbauer @jensens would you mind if I merge this one? :thinking: I will probably have to adapt a few things here and there on the jenkins side, and maybe even mr.roboto, so it is probably best that I handle it myself.

I will try to merge it quickly so it does not age :older_man:

**Comment by pbauer** [comment]
@gforcada Sure thing, tomorrow morning sound good?

**Comment by jensens** [comment]
Its still WIP. but once ready and py3 and py2 on 3 plip jobs are green please take over. I think I'll finish it today (famous last words).

**Comment by pbauer** [comment]
I added two new jobs: https://jenkins.plone.org/view/PLIPs/job/coredev_refactor_py2 and https://jenkins.plone.org/view/PLIPs/job/coredev_refactor_py3/ to test it. 

@gforcada Can you review it?

**Comment by gforcada** [comment]
Yes, I will have a look at night, let me know when I should take over

**Comment by jensens** [comment]
@gforcada so, IMO the buildout here overall looks fine, the tests are green. You can take over! If it is merged, then we can merge all the branches, let the merge-fest begin.

**Comment by jensens** [comment]
FTR: one open task is to edit the docs to reflect the changes, but I see this out of scope of this merge session. I will do this afterwards.

**Review by gforcada — APPROVED** [review]
I already force pushed some minor changes :)

**Pull request merged**
