### PR TITLE
Zope 4.3 for Plone 5.2

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I have added several checkouts and version updates in 5.2 today (Jenkins still running), which contains several of the version updates here (not all). So perhaps do a rebase and force push.

**Comment by mauritsvanrees** [comment]
I tried a rebase, which seems to work fine, and makes this PR smaller. I don't want to force push it though, because the core 5.2 jobs have not finished yet, so I don't know if it will be okay.

I did a small syntax error fix on the [plone.dexterity branch](https://github.com/plone/plone.dexterity/tree/zope-4.2.1) that you started, but which is not in the sources.cfg of this PR yet. With that, the plone.dexterity failures are gone. 

That leaves three other packages with failures, on Python 2 only. Progress!

I will leave it at that for now.

**Comment by jensens** [comment]
rebased, lets see:
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
7 failures in Py 2.7 , with 5 WebDAV related https://jenkins.plone.org/job/pull-request-5.2/1027/

**Comment by mauritsvanrees** [comment]
I pulled your changes and force pushed them with the plone.dexterity zope-4.2.1 branch added.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
We are on Zope 4.3 now! With only 2 tests failing in Archetypes.

**Comment by mauritsvanrees** [comment]
Very good!
I see they are the same tests that were already failing with Zope 4.2.1, so no difference there.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
I added zope.interface with the c3 ro branch and try to fix the EPI interface RO problem. 
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I have added missing checkouts: I did some releases last week, so not all were in the checkouts anymore.

@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I ran `bin/manage report --interactive` on 5.2 and used this to add more packages to the checkouts, like `plone.autoform` which you fixed for the newer zope.interface.
I have merged those changes into the branch.

@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
aye @mauritsvanrees  - thanks for taking care!

**Comment by mauritsvanrees** [comment]
Thanks for doing the bulk of the work @jensens !

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
With ATContentTypes this is the failure:

```
File "/Users/maurits/shared-eggs/cp27m/Products.ATContentTypes-3.0.2-py2.7.egg/Products/ATContentTypes/tests/http_access.txt", line 106, in http_access.txt
Failed example:
    print http(r"""
    HEAD /%s HTTP/1.1
    Authorization: Basic %s:%s
    """ % (fpath, user_name, user_password))
Differences (ndiff with -expected +actual):
      HTTP/1.1 200 OK
    - ...
      Content-Length: 1
    - ...
    + Content-Location: http://localhost/plone/Members/test_user_1_/
    + Content-Type: text/plain; charset=utf-8
    + Date: Sat, 21 Mar 2020 02:03:49 GMT
    + Etag: ts84756228.73
    + Last-Modified: Sat, 21 Mar 2020 02:03:49 GMT
    + <BLANKLINE>
```

So there is no line between `HTTP/1.1` and `Content-Length`.
When I remove the dots in between and run this test on current 5.2, I get this:

```
File "/Users/maurits/community/plone-coredev/5.2/src/Products.ATContentTypes/Products/ATContentTypes/tests/http_access.txt", line 106, in http_access.txt
Failed example:
    print http(r"""
    HEAD /%s HTTP/1.1
    Authorization: Basic %s:%s
    """ % (fpath, user_name, user_password))
Differences (ndiff with -expected +actual):
      HTTP/1.1 200 OK
    + Connection: close
      Content-Length: 1
    - ...
    + Content-Location: http://localhost/plone/Members/test_user_1_/
    + Content-Type: text/plain; charset=utf-8
    + Date: Sat, 21 Mar 2020 02:06:21 GMT
    + Etag: ts84756381.64
    + Last-Modified: Sat, 21 Mar 2020 02:06:21 GMT
    + <BLANKLINE>
```

So the difference is that on current 5.2 we have an extra line `Connection: close`.
I have no idea if that is correct or not. I guess we can ignore it.
I will create a branch and put it in the current PR.

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
I think the remaining problem in Archetypes is related to the brought back WebDAV support in Zope 4.2

**Comment by mauritsvanrees** [comment]
I suspect webdav too.

I have added an Archetypes branch where I use `manage_FTPget` instead of `manage_DAVget` in the marshall tests. That fixes it for me. Slightly unexpected, but I guess it is okay.

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Yes, all jobs are green!!!

**Comment by mauritsvanrees** [comment]
So... how should we handle this? One option:

1. Merge this PR. That will use various zope-4.2.1 branches.
2. Merge the various zope-4.2.1 branches to master.
3. Update `sources.cfg` to again use the master branches.

This should give a green build after each step.

**Comment by jensens** [comment]
... or we just merge this PR and all the branches and have some red builds in between. Same result, not that pretty, but less work with the same result.

**Comment by mauritsvanrees** [comment]
Okay, I am about to merge everything. Hold on tight.

**Comment by mauritsvanrees** [comment]
Done.

**Pull request merged**
