### PR TITLE
Add script to see how many circular dependencies exist

### PR DESCRIPTION
**Pull request by gforcada**
Just run:

```
bin/buildout -c jenkins-package-dependencies.cfg
bin/circular_deps
```

Which outputs:

```
Circular dependency between ('products.externalmethod', 'zope2')
Circular dependency between ('products.mailhost', 'zope2')
Circular dependency between ('plone.app.workflow', 'products.cmfplone')
Circular dependency between ('plone.app.dexterity', 'products.cmfplone')
Circular dependency between ('plone.app.controlpanel', 'products.cmfplone')
Circular dependency between ('plone.app.portlets', 'products.cmfplone')
Circular dependency between ('plone.app.theming', 'products.cmfplone')
Circular dependency between ('plone.app.widgets', 'products.cmfplone')
Circular dependency between ('plone.app.widgets', 'plone.app.z3cform')
Circular dependency between ('plone.app.registry', 'products.cmfplone')
Circular dependency between ('plone.app.contentrules', 'products.cmfplone')
Circular dependency between ('plone.app.users', 'products.cmfplone')
Circular dependency between ('plone.app.contenttypes', 'products.cmfplone')
Circular dependency between ('plone.app.discussion', 'products.cmfplone')
Circular dependency between ('products.standardcachemanagers', 'zope2')
Circular dependency between ('products.pythonscripts', 'zope2')
Circular dependency between ('products.zcatalog', 'zope2')
Circular dependency between ('plone.app.multilingual', 'products.cmfplone')
Circular dependency between ('plone.app.multilingual', 'archetypes.multilingual')
Circular dependency between ('plone.app.content', 'products.cmfplone')
Circular dependency between ('products.ofsp', 'zope2')
Circular dependency between ('plone.app.contentmenu', 'products.cmfplone')
Circular dependency between ('products.btreefolder2', 'zope2')
Circular dependency between ('plone.app.layout', 'products.cmfplone')
Circular dependency between ('plone.app.layout', 'plone.app.portlets')
Circular dependency between ('products.passwordresettool', 'products.cmfplone')
Circular dependency between ('plone.app.querystring', 'plone.app.vocabularies')
Circular dependency between ('products.zctextindex', 'zope2')
```

**NOTE:** it's probably _NOT_ worth merging this, but mostly as a way to see the tip of the iceberg regarding our forest of dependencies as (@jensens dubbed it) as there are a lot of dependencies not being declared at all on distributions setup.py's.

I pushed quite a few changes on `z3c.dependencychecker` so that it detects most of the dependencies.

Next steps should be to create a reporter for all distributions about their missing dependencies, so they can be fixed one at a time and then enjoy how the forest grows and grows :popcorn:

### CODE REVIEW

**Comment by thet** [comment]
great! looking forward for more results, better declared dependencies and resolved circular ones.

**Comment by jensens** [comment]
i like it! but i would put the buildout configuration in file to be used easily outside of jenkins context.

**Comment by bloodbare** [comment]
The CMFPlone circular dependencies on setup.py aren't normal as we use Products.CMFPlone to load all the dependencies of Plone ?

**Comment by gforcada** [comment]
@jensens as I stated on the first message this was supposed to _not_ be merged...

**Comment by jensens** [comment]
ops, my understanding was it should be merged. I try to revert.

**Comment by jensens** [comment]
done

**Pull request merged**
