### PR TITLE
[5.1] update mosaic versions

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jensens sorry but this has to be reverted because I've updated `plone.subrequest = 1.9.0` and this unfortunately does not pass in Plone 5.1 tests ...

**Comment by jensens** [comment]
does it work with 1.8.6?

**Comment by jensens** [comment]
reverted subrequest bump only for now

**Comment by petschki** [comment]
@jensens yes just tested with 1.8.6 and works ...I've removed the pin in my latest plone.app.mosaic PR https://github.com/plone/plone.app.mosaic/pull/441

**Pull request merged**
