### PR TITLE
Fix link to GitHub Team, Developers

### PR DESCRIPTION
**Pull request by stevepiercy**
People are still wandering into v5 docs, and this change will need a rebuild. @polyester

Refs: https://github.com/plone/documentation/pull/1485

### CODE REVIEW

**Review by davisagli — COMMENTED** [review]
Now it's necessary to check both https://github.com/orgs/plone/teams/contributors/members and https://github.com/orgs/plone/teams/developers/members, right?

**Comment by stevepiercy** [comment]
@davisagli yup, updated with current policy. One more review, if you please?

**Review by davisagli — APPROVED** [review]
It makes me wonder if we should add everyone from the Developers team to the Contributors team as well, so there's only one place to check. Thoughts, @fredvd?

Anyway, I think this is accurate for describing the status quo.

**Comment by stevepiercy** [comment]
Sorry, one more review, please. I forgot this is in reStructuredText and I cleaned up some wording to complete this section.

**Review by davisagli — APPROVED** [review]

**Pull request merged**
