### PR TITLE
Update `robotframework-browser=18.9.1`

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

I made some package releases, so Jenkins is swamped now, so I hold off on merging right now.  But feel free to do so.  Anything that helps getting more stable robot tests is welcome!

**Pull request merged**
