### PR TITLE
Fixed dead links/spelling/grammar

### PR DESCRIPTION
**Pull request by sgrepos**
Fixes:  N/A

Improves: Dead links/spelling/grammar

Changes proposed in this pull request: Updated dead links, corrected spelling and grammar errors

### CODE REVIEW

**Comment by sgrepos** [comment]
Just a heads up: I've signed the contributor's agreement already--unfortunately GitHub linked my other account and that's why the Agreement verifier check didn't pass

**Comment by gforcada** [comment]
@sgrepos hi, and welcome to Plone!

The agreement check, looks at the email address used on the commits. If you used a different email than the one you have in github, please add it to github as well.

Another possibility is a hiccup on the verifier, closing and re-opening the pull request usually fixes it. Let's see...

**Comment by sgrepos** [comment]
@gforcada Hey, I just added my e-mail into GitHub. I've already committed here before, but accidentally used a different e-mail.

**Comment by sgrepos** [comment]
@gforcada Update: looks like closing and re-opening the pull request fixed it. Thanks! :)

**Comment by gforcada** [comment]
@sgrepos thanks for updating the email!

Would you mind forward-porting these changes on the 5.2 branch as well?

**Pull request merged**
