### PR TITLE
New versions for Plone 6.0 [2023-06-12]

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Includes latests pip and setuptools.  I hope that does not bite us.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
We need to keep the 6.1 branch in sync here.

**Comment by mauritsvanrees** [comment]
> We need to keep the 6.1 branch in sync here.

Will do once this PR is green and merged.  Ping me if I forget, please. :-)  I am in favour of just copying over all files, and manually undoing any unwanted changes, instead of a complete merge with dozens of commits, but it is a minor preference.

I needed to downgrade Selenium due to an incompatibility, so try once more:

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
[One test fails](https://jenkins.plone.org/job/pull-request-6.0-3.11/677/testReport/junit/plone.app.content.tests.test_actions/ActionsDXTestCase/test_delete_wrong_object_by_acquisition_with_action/) due to the newer `Products.CMFCore` 3.1 which has explicit acquisition partially enabled.  I think we only want this in Plone 6.1, so I have reverted this back to 3.0.

I will open a separate issue in `plone.app.content` for the failing test.  It actually fails in a good way. :-)

@jenkins-plone-org please run jobs

**Pull request merged**
